package com.universalplatform.identity;

public enum SystemRoleKey {
    ORGANIZATION_OWNER,
    ORGANIZATION_ADMINISTRATOR,
    BRANCH_ADMINISTRATOR,
    ACADEMIC_ADMINISTRATOR,
    EXAM_CONTROLLER,
    FINANCE_ADMINISTRATOR,
    TEACHER,
    EVALUATOR,
    TEACHING_ASSISTANT,
    MENTOR,
    STUDENT,
    GUARDIAN,
    SUPPORT_OPERATOR,
    AUDITOR
}
