package com.universalplatform.commercial;
import com.universalplatform.audit.AuditService; import com.universalplatform.identity.*; import com.universalplatform.licensing.*; import com.universalplatform.security.*; import java.math.*; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service class CommercialService {
 private final TenantContext tenants; private final ActorContext actors; private final AuthorizationService auth; private final SubscriptionRepository subscriptions; private final WhiteLabelRepository whiteLabels; private final AuditService audit; private final Clock clock=Clock.systemUTC();
 CommercialService(TenantContext t,ActorContext a,AuthorizationService z,SubscriptionRepository s,WhiteLabelRepository w,AuditService au){tenants=t;actors=a;auth=z;subscriptions=s;whiteLabels=w;audit=au;}
 @Transactional(readOnly=true) SubscriptionView subscription(){auth.require(PermissionKey.COMMERCIAL_VIEW);Subscription s=require();return view(s);}
 @Transactional SubscriptionView configure(String plan,BigDecimal amount,String currency,boolean autoRenew,long expectedVersion){auth.require(PermissionKey.COMMERCIAL_MANAGE);Subscription s=require();if(s.licenseRevision()!=expectedVersion)throw new IllegalStateException("Subscription license revision was modified");s.configurePlan(plan,amount,currency,autoRenew);audit.record(s.tenantId(),actors.requireSubject(),"SUBSCRIPTION_PLAN_UPDATED","subscription",s.tenantId().toString());return view(s);}
 @Transactional SubscriptionView trial(int days){auth.require(PermissionKey.COMMERCIAL_MANAGE);if(days<1||days>365)throw new IllegalArgumentException("Trial must be 1-365 days");Subscription s=require();s.configureTrial(clock.instant().plus(Duration.ofDays(days)));audit.record(s.tenantId(),actors.requireSubject(),"SUBSCRIPTION_TRIAL_STARTED","subscription",s.tenantId().toString());return view(s);}
 @Transactional SubscriptionView grace(int days){auth.require(PermissionKey.COMMERCIAL_MANAGE);if(days<1||days>180)throw new IllegalArgumentException("Grace period must be 1-180 days");Subscription s=require();s.enterGrace(clock.instant().plus(Duration.ofDays(days)));audit.record(s.tenantId(),actors.requireSubject(),"SUBSCRIPTION_GRACE_STARTED","subscription",s.tenantId().toString());return view(s);}
 @Transactional SubscriptionView suspend(){auth.require(PermissionKey.COMMERCIAL_MANAGE);Subscription s=require();s.suspend();audit.record(s.tenantId(),actors.requireSubject(),"SUBSCRIPTION_SUSPENDED","subscription",s.tenantId().toString());return view(s);}
 @Transactional WhiteLabelView whiteLabel(String brand,String color,String logo,String favicon,String domain,boolean enabled,long expectedVersion){auth.require(PermissionKey.COMMERCIAL_MANAGE);UUID t=tenants.requireTenantId();WhiteLabelSettings w=whiteLabels.findById(t).orElseGet(()->new WhiteLabelSettings(t,brand,color,logo,favicon,domain,clock.instant()));if(w.version()!=expectedVersion&&whiteLabels.existsById(t))throw new IllegalStateException("White-label settings were modified");w.update(brand,color,logo,favicon,domain,enabled,clock.instant());whiteLabels.save(w);audit.record(t,actors.requireSubject(),"WHITE_LABEL_UPDATED","white-label",t.toString());return white(w);}
 @Transactional(readOnly=true) WhiteLabelView readWhiteLabel(){auth.require(PermissionKey.COMMERCIAL_VIEW);return white(whiteLabels.findById(tenants.requireTenantId()).orElseThrow(()->new IllegalArgumentException("White-label settings not configured")));}
 private Subscription require(){return subscriptions.findByTenantId(tenants.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Subscription not found"));}
 private SubscriptionView view(Subscription s){return new SubscriptionView(s.tenantId(),s.status(),s.planCode(),s.recurringAmount(),s.currency(),s.autoRenew(),s.startsAt(),s.graceEndsAt(),s.expiresAt(),s.trialEndsAt(),s.authorityKind(),s.externalLicenseId(),s.licenseRevision());}
 private WhiteLabelView white(WhiteLabelSettings w){return new WhiteLabelView(w.tenantId(),w.brandName(),w.primaryColor(),w.logoUrl(),w.faviconUrl(),w.customDomain(),w.enabled(),w.version());}
 record SubscriptionView(UUID tenantId,SubscriptionStatus status,String planCode,BigDecimal recurringAmount,String currency,boolean autoRenew,Instant startsAt,Instant graceEndsAt,Instant expiresAt,Instant trialEndsAt,LicenseAuthorityKind authorityKind,String externalLicenseId,long licenseRevision){}
 record WhiteLabelView(UUID tenantId,String brandName,String primaryColor,String logoUrl,String faviconUrl,String customDomain,boolean enabled,long version){}
}
