import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { createFinanceFee, createFinanceInvoice, fetchFinanceFees, fetchFinanceInvoices, issueFinanceInvoice, recordFinancePayment } from '../platform/api'
import type { CurrentIdentity } from '../platform/api'

export function FinanceWorkspace({ me }: { me: CurrentIdentity }) {
  const client = useQueryClient()
  const fees = useQuery({ queryKey: ['finance-fees'], queryFn: fetchFinanceFees })
  const invoices = useQuery({ queryKey: ['finance-invoices'], queryFn: fetchFinanceInvoices })
  const [message, setMessage] = useState('')
  const canManage = me.permissions.includes('FINANCE_MANAGE')
  const [draft, setDraft] = useState({ name: '', amount: '0.00', currency: 'USD' })
  const [invoice, setInvoice] = useState({ membershipId: '', amount: '0.00', currency: 'USD', dueOn: '' })
  const [payment, setPayment] = useState({ invoiceId: '', amount: '0.00', currency: 'USD' })
  async function createFee() { try { await createFinanceFee({ name: draft.name, amount: Number(draft.amount), currency: draft.currency, status: 'ACTIVE' }); setDraft({ name: '', amount: '0.00', currency: 'USD' }); await client.invalidateQueries({ queryKey: ['finance-fees'] }); setMessage('Fee saved.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Fee save failed') } }
  async function createInvoice() { try { await createFinanceInvoice({ membershipId: invoice.membershipId, totalAmount: Number(invoice.amount), currency: invoice.currency, dueOn: invoice.dueOn }); await client.invalidateQueries({ queryKey: ['finance-invoices'] }); setMessage('Invoice created.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Invoice creation failed') } }
  async function issue(id: string, version: number) { try { await issueFinanceInvoice(id, version); await client.invalidateQueries({ queryKey: ['finance-invoices'] }); setMessage('Invoice issued.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Issue failed') } }
  async function pay() { try { await recordFinancePayment(payment.invoiceId, { amount: Number(payment.amount), currency: payment.currency }); await client.invalidateQueries({ queryKey: ['finance-invoices'] }); setPayment({ invoiceId: '', amount: '0.00', currency: 'USD' }); setMessage('Payment captured and receipt issued.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Payment failed') } }
  return <div className="content-stack">
    <section className="hero-card"><p className="eyebrow">Finance</p><h3>Fees, invoices and collections</h3><p>Tenant-scoped financial records are managed server-side with optimistic versions and a provider-neutral payment boundary.</p>{message && <p className="muted">{message}</p>}</section>
    {canManage && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Catalog</p><h3>Institution fees</h3></div></div><div className="form-grid"><label>Name<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Amount<input type="number" step="0.01" min="0" value={draft.amount} onChange={e => setDraft({ ...draft, amount: e.target.value })} /></label><label>Currency<input maxLength={3} value={draft.currency} onChange={e => setDraft({ ...draft, currency: e.target.value.toUpperCase() })} /></label><div className="form-actions"><button className="primary-button" onClick={() => void createFee()} disabled={!draft.name}>Create fee</button></div></div></section>}
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Fee catalog</p><h3>Configured fees</h3></div></div>{fees.isPending ? <p className="muted">Loading…</p> : fees.isError ? <p className="error-text">{fees.error.message}</p> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>Amount</th><th>Status</th></tr></thead><tbody>{fees.data.map(f => <tr key={f.id}><td>{f.name}</td><td>{f.currency} {f.amount.toFixed(2)}</td><td>{f.status}</td></tr>)}</tbody></table></div>}</section>
    {canManage && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Billing</p><h3>Create invoice</h3></div></div><div className="form-grid"><label>Membership ID<input value={invoice.membershipId} onChange={e => setInvoice({ ...invoice, membershipId: e.target.value })} /></label><label>Total<input type="number" step="0.01" min="0.01" value={invoice.amount} onChange={e => setInvoice({ ...invoice, amount: e.target.value })} /></label><label>Currency<input maxLength={3} value={invoice.currency} onChange={e => setInvoice({ ...invoice, currency: e.target.value.toUpperCase() })} /></label><label>Due on<input type="date" value={invoice.dueOn} onChange={e => setInvoice({ ...invoice, dueOn: e.target.value })} /></label><div className="form-actions"><button className="primary-button" onClick={() => void createInvoice()} disabled={!invoice.membershipId || !invoice.dueOn}>Create invoice</button></div></div></section>}
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Receivables</p><h3>Invoices</h3></div></div>{invoices.isPending ? <p className="muted">Loading…</p> : invoices.isError ? <p className="error-text">{invoices.error.message}</p> : <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Member</th><th>Total</th><th>Paid</th><th>Status</th><th /></tr></thead><tbody>{invoices.data.items.map(i => <tr key={i.id}><td>{i.invoiceNumber}</td><td><code>{i.membershipId.slice(0,8)}</code></td><td>{i.currency} {i.totalAmount.toFixed(2)}</td><td>{i.currency} {i.paidAmount.toFixed(2)}</td><td>{i.status}</td><td>{canManage && i.status === 'DRAFT' ? <button className="text-button" onClick={() => void issue(i.id, i.version)}>Issue</button> : null}</td></tr>)}</tbody></table></div>}</section>
    {canManage && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Collection</p><h3>Capture payment</h3></div></div><div className="form-grid"><label>Invoice ID<input value={payment.invoiceId} onChange={e => setPayment({ ...payment, invoiceId: e.target.value })} /></label><label>Amount<input type="number" step="0.01" min="0.01" value={payment.amount} onChange={e => setPayment({ ...payment, amount: e.target.value })} /></label><label>Currency<input maxLength={3} value={payment.currency} onChange={e => setPayment({ ...payment, currency: e.target.value.toUpperCase() })} /></label><div className="form-actions"><button className="primary-button" onClick={() => void pay()} disabled={!payment.invoiceId}>Capture payment</button></div></div></section>}
  </div>
}
