import { useState } from 'react'
import type { FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { completeUpload, createFileResource, createTextResource, fetchResources, initiateUpload, uploadChunk } from '../platform/api'
import type { CurrentIdentity, DownloadPolicy, ResourceVisibility } from '../platform/api'
const has=(me:CurrentIdentity,p:string)=>me.permissions.includes(p as never)||me.primaryBranchPermissions.includes(p as never)
export function ContentWorkspace({me}:{me:CurrentIdentity}){
 const qc=useQueryClient();const resources=useQuery({queryKey:['resources'],queryFn:fetchResources});const [progress,setProgress]=useState('')
 const text=useMutation({mutationFn:createTextResource,onSuccess:()=>void qc.invalidateQueries({queryKey:['resources']})})
 async function uploadFile(file:File,title:string,visibility:ResourceVisibility,downloadPolicy:DownloadPolicy){const session=await initiateUpload({fileName:file.name,contentType:file.type||'application/octet-stream',expectedBytes:file.size,provider:'LOCAL'});const chunkSize=8*1024*1024;let offset=0;while(offset<file.size){const chunk=file.slice(offset,Math.min(file.size,offset+chunkSize));const updated=await uploadChunk(session.id,offset,chunk);offset=updated.receivedBytes;setProgress(`${Math.round(offset/file.size*100)}%`)}const stored=await completeUpload(session.id);await createFileResource({title,kind:file.type.startsWith('video/')?'VIDEO':file.type.startsWith('audio/')?'AUDIO':'DOCUMENT',storageObjectId:stored.id,visibility,downloadPolicy});setProgress('Complete');void qc.invalidateQueries({queryKey:['resources']})}
 function submitText(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);text.mutate({title:String(d.get('title')),text:String(d.get('text')),visibility:String(d.get('visibility')) as ResourceVisibility,downloadPolicy:String(d.get('downloadPolicy')) as DownloadPolicy},{onSuccess:()=>f.reset()})}
 async function submitFile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f),file=(f.elements.namedItem('file') as HTMLInputElement).files?.[0];if(!file)return;await uploadFile(file,String(d.get('title')),String(d.get('visibility')) as ResourceVisibility,String(d.get('downloadPolicy')) as DownloadPolicy);f.reset()}
 return <div className="content-stack">{has(me,'CONTENT_MANAGE')&&<><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Authoring</p><h3>Create text note</h3></div></div><form className="form-grid" onSubmit={submitText}><label>Title<input name="title" required maxLength={300}/></label><label>Visibility<select name="visibility" defaultValue="ENROLLED_LEARNERS"><option>PRIVATE</option><option>STAFF</option><option>ENROLLED_LEARNERS</option><option>TENANT</option></select></label><label>Download policy<select name="downloadPolicy" defaultValue="NO_DOWNLOAD"><option>NO_DOWNLOAD</option><option>DOWNLOAD_ALLOWED</option><option>STREAM_ONLY</option></select></label><label className="wide">Note<textarea name="text" required rows={8}/></label><div className="form-actions"><button className="primary-button">Publish note</button></div></form></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Resumable upload</p><h3>Add file resource</h3></div></div><form className="form-grid" onSubmit={e=>void submitFile(e)}><label>Title<input name="title" required/></label><label>File<input name="file" type="file" required/></label><label>Visibility<select name="visibility" defaultValue="ENROLLED_LEARNERS"><option>PRIVATE</option><option>STAFF</option><option>ENROLLED_LEARNERS</option><option>TENANT</option></select></label><label>Download policy<select name="downloadPolicy"><option>DOWNLOAD_ALLOWED</option><option>STREAM_ONLY</option><option>NO_DOWNLOAD</option></select></label><div className="form-actions"><button className="primary-button">Upload and publish</button><span>{progress}</span></div></form></section></>}
 <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Learning library</p><h3>Resources</h3></div><span className="count-badge">{resources.data?.totalElements??0}</span></div>{resources.isPending?<p>Loading…</p>:resources.isError?<p role="alert">{resources.error.message}</p>:<div className="card-grid">{resources.data.items.map(r=><article className="mini-card" key={r.id}><div className="mini-card-title"><strong>{r.title}</strong><span>v{r.currentVersion}</span></div><p>{r.description??r.kind}</p><div className="chip-row compact"><span className="chip">{r.visibility}</span><span className="chip">{r.downloadPolicy}</span></div></article>)}</div>}</section></div>
}
