-- Extend persisted built-in roles for scheduling and communication. Runtime role reconciliation mirrors this map.
INSERT INTO role_permission (role_id, permission_key)
SELECT rd.id, grant_map.permission_key
FROM role_definition rd
JOIN (VALUES
    ('ORGANIZATION_OWNER', 'SCHEDULE_VIEW'), ('ORGANIZATION_OWNER', 'SCHEDULE_MANAGE'),
    ('ORGANIZATION_OWNER', 'SCHEDULE_CONFLICT_OVERRIDE'), ('ORGANIZATION_OWNER', 'ANNOUNCEMENTS_VIEW'),
    ('ORGANIZATION_OWNER', 'ANNOUNCEMENTS_MANAGE'), ('ORGANIZATION_OWNER', 'NOTIFICATION_OPERATIONS_VIEW'),
    ('ORGANIZATION_ADMINISTRATOR', 'SCHEDULE_VIEW'), ('ORGANIZATION_ADMINISTRATOR', 'SCHEDULE_MANAGE'),
    ('ORGANIZATION_ADMINISTRATOR', 'SCHEDULE_CONFLICT_OVERRIDE'), ('ORGANIZATION_ADMINISTRATOR', 'ANNOUNCEMENTS_VIEW'),
    ('ORGANIZATION_ADMINISTRATOR', 'ANNOUNCEMENTS_MANAGE'), ('ORGANIZATION_ADMINISTRATOR', 'NOTIFICATION_OPERATIONS_VIEW'),
    ('BRANCH_ADMINISTRATOR', 'SCHEDULE_VIEW'), ('BRANCH_ADMINISTRATOR', 'SCHEDULE_MANAGE'),
    ('BRANCH_ADMINISTRATOR', 'ANNOUNCEMENTS_VIEW'), ('BRANCH_ADMINISTRATOR', 'ANNOUNCEMENTS_MANAGE'),
    ('ACADEMIC_ADMINISTRATOR', 'SCHEDULE_VIEW'), ('ACADEMIC_ADMINISTRATOR', 'SCHEDULE_MANAGE'),
    ('ACADEMIC_ADMINISTRATOR', 'ANNOUNCEMENTS_VIEW'), ('ACADEMIC_ADMINISTRATOR', 'ANNOUNCEMENTS_MANAGE'),
    ('EXAM_CONTROLLER', 'SCHEDULE_VIEW'), ('EXAM_CONTROLLER', 'ANNOUNCEMENTS_VIEW'),
    ('FINANCE_ADMINISTRATOR', 'SCHEDULE_VIEW'), ('FINANCE_ADMINISTRATOR', 'ANNOUNCEMENTS_VIEW'),
    ('TEACHER', 'SCHEDULE_VIEW'), ('TEACHER', 'ANNOUNCEMENTS_VIEW'),
    ('EVALUATOR', 'SCHEDULE_VIEW'), ('EVALUATOR', 'ANNOUNCEMENTS_VIEW'),
    ('TEACHING_ASSISTANT', 'SCHEDULE_VIEW'), ('TEACHING_ASSISTANT', 'ANNOUNCEMENTS_VIEW'),
    ('MENTOR', 'SCHEDULE_VIEW'), ('MENTOR', 'ANNOUNCEMENTS_VIEW'),
    ('STUDENT', 'SCHEDULE_VIEW'), ('STUDENT', 'ANNOUNCEMENTS_VIEW'),
    ('GUARDIAN', 'SCHEDULE_VIEW'), ('GUARDIAN', 'ANNOUNCEMENTS_VIEW'),
    ('SUPPORT_OPERATOR', 'SCHEDULE_VIEW'), ('SUPPORT_OPERATOR', 'ANNOUNCEMENTS_VIEW'),
    ('SUPPORT_OPERATOR', 'NOTIFICATION_OPERATIONS_VIEW'),
    ('AUDITOR', 'SCHEDULE_VIEW'), ('AUDITOR', 'ANNOUNCEMENTS_VIEW'), ('AUDITOR', 'NOTIFICATION_OPERATIONS_VIEW')
) AS grant_map(system_key, permission_key)
ON rd.system_key = grant_map.system_key
ON CONFLICT (role_id, permission_key) DO NOTHING;
