INSERT INTO role_permission (role_id, permission_key)
SELECT rd.id, grant_map.permission_key FROM role_definition rd JOIN (VALUES
 ('ORGANIZATION_OWNER','CONTENT_VIEW'),('ORGANIZATION_OWNER','CONTENT_MANAGE'),
 ('ORGANIZATION_ADMINISTRATOR','CONTENT_VIEW'),('ORGANIZATION_ADMINISTRATOR','CONTENT_MANAGE'),
 ('BRANCH_ADMINISTRATOR','CONTENT_VIEW'),
 ('ACADEMIC_ADMINISTRATOR','CONTENT_VIEW'),('ACADEMIC_ADMINISTRATOR','CONTENT_MANAGE'),
 ('TEACHER','CONTENT_VIEW'),('TEACHER','CONTENT_MANAGE'),('TEACHING_ASSISTANT','CONTENT_VIEW'),('TEACHING_ASSISTANT','CONTENT_MANAGE'),
 ('MENTOR','CONTENT_VIEW'),('MENTOR','CONTENT_MANAGE'),('EVALUATOR','CONTENT_VIEW'),('EXAM_CONTROLLER','CONTENT_VIEW'),
 ('STUDENT','CONTENT_VIEW'),('GUARDIAN','CONTENT_VIEW'),('SUPPORT_OPERATOR','CONTENT_VIEW'),('AUDITOR','CONTENT_VIEW')
) AS grant_map(system_key,permission_key) ON rd.system_key=grant_map.system_key
ON CONFLICT(role_id,permission_key) DO NOTHING;
