INSERT INTO role_permission (role_id, permission_key)
SELECT rd.id, grant_map.permission_key
FROM role_definition rd
JOIN (VALUES
    ('ORGANIZATION_OWNER','ASSESSMENTS_VIEW'), ('ORGANIZATION_OWNER','ASSESSMENTS_MANAGE'), ('ORGANIZATION_OWNER','ASSESSMENTS_TAKE'),
    ('ORGANIZATION_ADMINISTRATOR','ASSESSMENTS_VIEW'), ('ORGANIZATION_ADMINISTRATOR','ASSESSMENTS_MANAGE'), ('ORGANIZATION_ADMINISTRATOR','ASSESSMENTS_TAKE'),
    ('BRANCH_ADMINISTRATOR','ASSESSMENTS_VIEW'), ('BRANCH_ADMINISTRATOR','ASSESSMENTS_MANAGE'),
    ('ACADEMIC_ADMINISTRATOR','ASSESSMENTS_VIEW'), ('ACADEMIC_ADMINISTRATOR','ASSESSMENTS_MANAGE'),
    ('EXAM_CONTROLLER','ASSESSMENTS_VIEW'), ('EXAM_CONTROLLER','ASSESSMENTS_MANAGE'),
    ('TEACHER','ASSESSMENTS_VIEW'), ('TEACHER','ASSESSMENTS_MANAGE'), ('TEACHER','ASSESSMENTS_TAKE'),
    ('EVALUATOR','ASSESSMENTS_VIEW'), ('EVALUATOR','ASSESSMENTS_TAKE'),
    ('TEACHING_ASSISTANT','ASSESSMENTS_VIEW'), ('TEACHING_ASSISTANT','ASSESSMENTS_TAKE'),
    ('MENTOR','ASSESSMENTS_VIEW'), ('MENTOR','ASSESSMENTS_TAKE'),
    ('STUDENT','ASSESSMENTS_VIEW'), ('STUDENT','ASSESSMENTS_TAKE'),
    ('AUDITOR','ASSESSMENTS_VIEW')
) AS grant_map(system_key, permission_key) ON rd.system_key = grant_map.system_key
ON CONFLICT (role_id, permission_key) DO NOTHING;
