INSERT INTO role_permission (role_id, permission_key)
SELECT rd.id, grant_map.permission_key
FROM role_definition rd
JOIN (VALUES
    ('ORGANIZATION_OWNER','GRADING_VIEW'), ('ORGANIZATION_OWNER','GRADING_MANAGE'), ('ORGANIZATION_OWNER','REVIEW_VIEW'), ('ORGANIZATION_OWNER','REVIEW_SUBMIT'), ('ORGANIZATION_OWNER','REVIEW_MANAGE'),
    ('ORGANIZATION_ADMINISTRATOR','GRADING_VIEW'), ('ORGANIZATION_ADMINISTRATOR','GRADING_MANAGE'), ('ORGANIZATION_ADMINISTRATOR','REVIEW_VIEW'), ('ORGANIZATION_ADMINISTRATOR','REVIEW_SUBMIT'), ('ORGANIZATION_ADMINISTRATOR','REVIEW_MANAGE'),
    ('BRANCH_ADMINISTRATOR','GRADING_VIEW'), ('BRANCH_ADMINISTRATOR','GRADING_MANAGE'), ('BRANCH_ADMINISTRATOR','REVIEW_VIEW'), ('BRANCH_ADMINISTRATOR','REVIEW_MANAGE'),
    ('ACADEMIC_ADMINISTRATOR','GRADING_VIEW'), ('ACADEMIC_ADMINISTRATOR','GRADING_MANAGE'), ('ACADEMIC_ADMINISTRATOR','REVIEW_VIEW'), ('ACADEMIC_ADMINISTRATOR','REVIEW_MANAGE'),
    ('EXAM_CONTROLLER','GRADING_VIEW'), ('EXAM_CONTROLLER','GRADING_MANAGE'), ('EXAM_CONTROLLER','REVIEW_VIEW'), ('EXAM_CONTROLLER','REVIEW_MANAGE'),
    ('TEACHER','GRADING_VIEW'), ('TEACHER','GRADING_MANAGE'), ('TEACHER','REVIEW_VIEW'), ('TEACHER','REVIEW_SUBMIT'),
    ('EVALUATOR','GRADING_VIEW'), ('EVALUATOR','GRADING_MANAGE'), ('EVALUATOR','REVIEW_VIEW'), ('EVALUATOR','REVIEW_MANAGE'),
    ('TEACHING_ASSISTANT','GRADING_VIEW'), ('TEACHING_ASSISTANT','REVIEW_VIEW'), ('TEACHING_ASSISTANT','REVIEW_SUBMIT'),
    ('MENTOR','GRADING_VIEW'), ('MENTOR','REVIEW_VIEW'), ('MENTOR','REVIEW_SUBMIT'),
    ('STUDENT','REVIEW_VIEW'), ('STUDENT','REVIEW_SUBMIT'),
    ('AUDITOR','GRADING_VIEW'), ('AUDITOR','REVIEW_VIEW')
) AS grant_map(system_key, permission_key) ON rd.system_key = grant_map.system_key
ON CONFLICT (role_id, permission_key) DO NOTHING;
