package com.universalplatform.content;
import com.universalplatform.storage.StorageProviderType; import jakarta.servlet.http.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.io.*; import java.time.Instant; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody;
@RestController @RequestMapping("/api/v1") class ContentController {
 private final UploadService uploads;private final ContentService content;ContentController(UploadService u,ContentService c){uploads=u;content=c;}
 @PostMapping("/uploads") UploadService.UploadView initiate(@Valid @RequestBody InitiateUpload r)throws IOException{return uploads.initiate(r.fileName,r.contentType,r.expectedBytes,r.sha256,r.provider);}
 @PutMapping(value="/uploads/{id}/content",consumes=MediaType.APPLICATION_OCTET_STREAM_VALUE) UploadService.UploadView chunk(@PathVariable UUID id,@RequestHeader("Upload-Offset") long offset,@RequestHeader(HttpHeaders.CONTENT_LENGTH) long length,HttpServletRequest request)throws IOException{return uploads.append(id,offset,request.getInputStream(),length);}
 @PostMapping("/uploads/{id}/complete") UploadService.StorageView complete(@PathVariable UUID id)throws Exception{return uploads.finalizeUpload(id);}
 @DeleteMapping("/uploads/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void abort(@PathVariable UUID id)throws IOException{uploads.abort(id);}
 @GetMapping("/resources") ContentPage<ContentService.ResourceView> list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="25")int size){return content.list(page,size);}
 @PostMapping("/resources/text") ContentService.ResourceView text(@Valid @RequestBody TextResource r){return content.createText(new ContentService.CreateText(r.title,r.description,r.text,r.changeNote,r.courseId,r.moduleId,r.classSessionId,r.language,r.visibility,r.downloadPolicy,r.releaseAt,r.expiresAt));}
 @PostMapping("/resources/file") ContentService.ResourceView file(@Valid @RequestBody FileResource r){return content.createFile(new ContentService.CreateFile(r.title,r.description,r.kind,r.storageObjectId,r.changeNote,r.courseId,r.moduleId,r.classSessionId,r.language,r.visibility,r.downloadPolicy,r.releaseAt,r.expiresAt));}
 @PostMapping("/resources/{id}/versions/text") ContentService.ResourceView textVersion(@PathVariable UUID id,@RequestBody TextVersion r){return content.addTextVersion(id,r.text,r.changeNote);}
 @PostMapping("/resources/{id}/versions/file") ContentService.ResourceView fileVersion(@PathVariable UUID id,@RequestBody FileVersion r){return content.addFileVersion(id,r.storageObjectId,r.changeNote);}
 @GetMapping("/resources/{id}/versions") List<ContentService.VersionView> versions(@PathVariable UUID id){return content.versionHistory(id);}
 @GetMapping("/resources/{id}/download") ResponseEntity<StreamingResponseBody> download(@PathVariable UUID id,@RequestParam(required=false)Integer version){var h=content.download(id,version);StreamingResponseBody body=out->{try(InputStream in=h.opener().open()){in.transferTo(out);}};return ResponseEntity.ok().contentType(MediaType.parseMediaType(h.contentType())).contentLength(h.length()).header(HttpHeaders.CONTENT_DISPOSITION,(h.policy()==DownloadPolicy.STREAM_ONLY?"inline":"attachment")+"; filename*=UTF-8''"+java.net.URLEncoder.encode(h.fileName(),java.nio.charset.StandardCharsets.UTF_8)).body(body);}
 @PutMapping("/content-retention") ContentService.RetentionView retention(@RequestBody RetentionRequest r){return content.updateRetention(r.defaultRetentionDays,r.deletedObjectGraceDays,r.retainVersions,r.expectedVersion);}
 record InitiateUpload(@NotBlank String fileName,String contentType,@PositiveOrZero long expectedBytes,String sha256,@NotNull StorageProviderType provider){} record TextResource(@NotBlank String title,String description,@NotBlank String text,String changeNote,UUID courseId,UUID moduleId,UUID classSessionId,String language,@NotNull ResourceVisibility visibility,@NotNull DownloadPolicy downloadPolicy,Instant releaseAt,Instant expiresAt){} record FileResource(@NotBlank String title,String description,@NotNull ResourceKind kind,@NotNull UUID storageObjectId,String changeNote,UUID courseId,UUID moduleId,UUID classSessionId,String language,@NotNull ResourceVisibility visibility,@NotNull DownloadPolicy downloadPolicy,Instant releaseAt,Instant expiresAt){} record TextVersion(@NotBlank String text,String changeNote){} record FileVersion(@NotNull UUID storageObjectId,String changeNote){} record RetentionRequest(Integer defaultRetentionDays,int deletedObjectGraceDays,boolean retainVersions,long expectedVersion){}
}
