package com.universalplatform.content;
import com.universalplatform.audit.AuditService; import com.universalplatform.curriculum.CurriculumDirectory; import com.universalplatform.scheduling.ScheduleDirectory; import com.universalplatform.enrollment.EnrollmentDirectory; import com.universalplatform.identity.*; import com.universalplatform.security.*; import com.universalplatform.storage.*;
import java.io.*; import java.time.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service
class ContentService {
 private final CurriculumDirectory curriculum;private final ScheduleDirectory schedules;private final TenantContext tenants;private final ActorContext actors;private final AuthorizationService auth;private final MembershipDirectory memberships;private final EnrollmentDirectory enrollment;private final LearningResourceRepository resources;private final LearningResourceVersionRepository versions;private final StorageObjectRepository objects;private final StorageAdapterRegistry adapters;private final ContentRetentionPolicyRepository retention;private final AuditService audit;private final Clock clock=Clock.systemUTC();
 ContentService(CurriculumDirectory curriculum,ScheduleDirectory schedules,TenantContext t,ActorContext a,AuthorizationService au,MembershipDirectory m,EnrollmentDirectory e,LearningResourceRepository r,LearningResourceVersionRepository v,StorageObjectRepository o,StorageAdapterRegistry ad,ContentRetentionPolicyRepository rp,AuditService audit){this.curriculum=curriculum;this.schedules=schedules;tenants=t;actors=a;auth=au;memberships=m;enrollment=e;resources=r;versions=v;objects=o;adapters=ad;retention=rp;this.audit=audit;}
 @Transactional(readOnly=true) ContentPage<ResourceView> list(int page,int size){auth.require(PermissionKey.CONTENT_VIEW);UUID tenant=tenants.requireTenantId();PageRequest pageable=PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.DESC,"updatedAt"));Page<LearningResource> p;if(auth.has(PermissionKey.CONTENT_MANAGE)){p=resources.findAllByTenantId(tenant,pageable);}else{UUID membershipId=memberships.current().membershipId();Set<UUID> courses=enrollment.activeCourseIdsForMembership(membershipId);if(courses.isEmpty())courses=Set.of(new UUID(0L,0L));p=resources.findVisible(tenant,actors.requireSubject(),auth.has(PermissionKey.TEACHING_ASSIGNMENTS_VIEW),courses,clock.instant(),pageable);}return new ContentPage<>(p.getContent().stream().map(this::view).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @Transactional ResourceView createText(CreateText c){auth.require(PermissionKey.CONTENT_MANAGE);validateWindow(c.releaseAt,c.expiresAt);validateScope(c.courseId,c.moduleId,c.classSessionId);UUID tenant=tenants.requireTenantId();Instant now=clock.instant();Instant expiry=effectiveExpiry(tenant,c.expiresAt,now);LearningResource r=resources.save(new LearningResource(UUID.randomUUID(),tenant,actors.requireSubject(),required(c.title,300),nullable(c.description,4000),ResourceKind.TEXT_NOTE,c.courseId,c.moduleId,c.classSessionId,c.language,c.visibility,c.downloadPolicy,c.releaseAt,expiry,now));versions.save(new LearningResourceVersion(UUID.randomUUID(),tenant,r.id,1,null,required(c.text,1_000_000),c.changeNote,actors.requireSubject(),now));audit.record(tenant,actors.requireSubject(),"LEARNING_RESOURCE_CREATED","learning_resource",r.id.toString());return view(r);}
 @Transactional ResourceView createFile(CreateFile c){auth.require(PermissionKey.CONTENT_MANAGE);validateWindow(c.releaseAt,c.expiresAt);validateScope(c.courseId,c.moduleId,c.classSessionId);UUID tenant=tenants.requireTenantId();Instant expiry=effectiveExpiry(tenant,c.expiresAt,clock.instant());StorageObject o=objects.findByTenantIdAndId(tenant,c.storageObjectId).orElseThrow(()->new IllegalArgumentException("Storage object not found"));if(o.status!=StorageObjectStatus.AVAILABLE)throw new IllegalStateException("Storage object is unavailable");Instant now=clock.instant();LearningResource r=resources.save(new LearningResource(UUID.randomUUID(),tenant,actors.requireSubject(),required(c.title,300),nullable(c.description,4000),c.kind,c.courseId,c.moduleId,c.classSessionId,c.language,c.visibility,c.downloadPolicy,c.releaseAt,expiry,now));versions.save(new LearningResourceVersion(UUID.randomUUID(),tenant,r.id,1,o.id,null,c.changeNote,actors.requireSubject(),now));audit.record(tenant,actors.requireSubject(),"LEARNING_RESOURCE_CREATED","learning_resource",r.id.toString());return view(r);}
 @Transactional ResourceView addTextVersion(UUID id,String text,String note){auth.require(PermissionKey.CONTENT_MANAGE);LearningResource r=require(id);r.nextVersion(clock.instant());versions.save(new LearningResourceVersion(UUID.randomUUID(),r.tenantId,r.id,r.currentVersion,null,required(text,1_000_000),note,actors.requireSubject(),clock.instant()));audit.record(r.tenantId,actors.requireSubject(),"LEARNING_RESOURCE_VERSION_CREATED","learning_resource",r.id.toString());return view(r);}
 @Transactional ResourceView addFileVersion(UUID id,UUID objectId,String note){auth.require(PermissionKey.CONTENT_MANAGE);LearningResource r=require(id);StorageObject o=objects.findByTenantIdAndId(r.tenantId,objectId).orElseThrow();if(o.status!=StorageObjectStatus.AVAILABLE)throw new IllegalStateException("Storage object unavailable");r.nextVersion(clock.instant());versions.save(new LearningResourceVersion(UUID.randomUUID(),r.tenantId,r.id,r.currentVersion,o.id,null,note,actors.requireSubject(),clock.instant()));return view(r);}
 @Transactional(readOnly=true) List<VersionView> versionHistory(UUID id){LearningResource r=requireReadable(id);return versions.findAllByTenantIdAndResourceIdOrderByVersionNumberDesc(r.tenantId,r.id).stream().map(v->new VersionView(v.versionNumber,v.storageObjectId,v.textualContent,v.changeNote,v.createdAt)).toList();}
 @Transactional(readOnly=true) DownloadHandle download(UUID id,Integer version){LearningResource r=requireReadable(id);if(r.downloadPolicy==DownloadPolicy.NO_DOWNLOAD)throw new IllegalStateException("Downloads are disabled for this resource");LearningResourceVersion v=version==null?versions.findByTenantIdAndResourceIdAndVersionNumber(r.tenantId,r.id,r.currentVersion).orElseThrow():versions.findByTenantIdAndResourceIdAndVersionNumber(r.tenantId,r.id,version).orElseThrow();if(v.storageObjectId==null)throw new IllegalArgumentException("Text resources do not have a file download");StorageObject o=objects.findByTenantIdAndId(r.tenantId,v.storageObjectId).orElseThrow();return new DownloadHandle(o.contentType,o.sizeBytes,o.objectKey,r.downloadPolicy,()->adapters.require(o.provider).open(o.locator));}
 @Transactional RetentionView updateRetention(Integer days,int grace,boolean retain,long expected){auth.require(PermissionKey.CONTENT_MANAGE);UUID t=tenants.requireTenantId();ContentRetentionPolicy p=retention.findById(t).orElseGet(()->new ContentRetentionPolicy(t,clock.instant()));if(p.version!=expected&&retention.existsById(t))throw new IllegalStateException("Retention policy was modified");if(days!=null&&days<1||grace<0)throw new IllegalArgumentException("Invalid retention policy");p.defaultRetentionDays=days;p.deletedObjectGraceDays=grace;p.retainVersions=retain;p.updatedAt=clock.instant();retention.save(p);return new RetentionView(days,grace,retain,p.version);}
 private LearningResource require(UUID id){return resources.findByTenantIdAndId(tenants.requireTenantId(),id).orElseThrow(()->new IllegalArgumentException("Resource not found"));} private LearningResource requireReadable(UUID id){auth.require(PermissionKey.CONTENT_VIEW);LearningResource r=require(id);if(!canRead(r))throw new IllegalArgumentException("Resource not found");return r;}
 private boolean canRead(LearningResource r){Instant n=clock.instant();if(r.releaseAt!=null&&n.isBefore(r.releaseAt)||r.expiresAt!=null&&!n.isBefore(r.expiresAt))return auth.has(PermissionKey.CONTENT_MANAGE);if(auth.has(PermissionKey.CONTENT_MANAGE)||r.visibility==ResourceVisibility.TENANT)return true;if(r.visibility==ResourceVisibility.PRIVATE)return r.createdBy.equals(actors.requireSubject());if(r.visibility==ResourceVisibility.STAFF)return auth.has(PermissionKey.TEACHING_ASSIGNMENTS_VIEW);if(r.visibility==ResourceVisibility.ENROLLED_LEARNERS&&r.courseId!=null){UUID m=memberships.current().membershipId();return enrollment.activeCourseIdsForMembership(m).contains(r.courseId);}return false;}
 private ResourceView view(LearningResource r){return new ResourceView(r.id,r.stableKey,r.title,r.description,r.resourceKind,r.courseId,r.moduleId,r.classSessionId,r.language,r.visibility,r.downloadPolicy,r.releaseAt,r.expiresAt,r.currentVersion,r.createdAt,r.version);}
 private Instant effectiveExpiry(UUID tenantId,Instant requested,Instant now){if(requested!=null)return requested;return retention.findById(tenantId).map(p->p.defaultRetentionDays==null?null:now.plus(Duration.ofDays(p.defaultRetentionDays))).orElse(null);}
 private void validateScope(UUID courseId,UUID moduleId,UUID classSessionId){if(courseId!=null)curriculum.requireCourse(courseId);if(moduleId!=null)curriculum.requireModule(moduleId);if(classSessionId!=null)schedules.requireClassSession(classSessionId);}
 private static void validateWindow(Instant a,Instant b){if(a!=null&&b!=null&&!b.isAfter(a))throw new IllegalArgumentException("Expiration must be after release");}private static String required(String s,int max){if(s==null||s.isBlank())throw new IllegalArgumentException("Value is required");String n=s.trim();if(n.length()>max)throw new IllegalArgumentException("Value is too long");return n;}private static String nullable(String s,int max){if(s==null||s.isBlank())return null;return required(s,max);}
 record CreateText(String title,String description,String text,String changeNote,UUID courseId,UUID moduleId,UUID classSessionId,String language,ResourceVisibility visibility,DownloadPolicy downloadPolicy,Instant releaseAt,Instant expiresAt){} record CreateFile(String title,String description,ResourceKind kind,UUID storageObjectId,String changeNote,UUID courseId,UUID moduleId,UUID classSessionId,String language,ResourceVisibility visibility,DownloadPolicy downloadPolicy,Instant releaseAt,Instant expiresAt){}
 record ResourceView(UUID id,UUID stableKey,String title,String description,ResourceKind kind,UUID courseId,UUID moduleId,UUID classSessionId,String language,ResourceVisibility visibility,DownloadPolicy downloadPolicy,Instant releaseAt,Instant expiresAt,int currentVersion,Instant createdAt,long version){} record VersionView(int version,UUID storageObjectId,String text,String changeNote,Instant createdAt){} record RetentionView(Integer defaultRetentionDays,int deletedObjectGraceDays,boolean retainVersions,long version){} record DownloadHandle(String contentType,long length,String fileName,DownloadPolicy policy,StreamOpener opener){} interface StreamOpener{InputStream open()throws IOException;}
}
