package com.universalplatform.assessment;

import com.universalplatform.audit.AuditService;
import com.universalplatform.enrollment.EnrollmentDirectory;
import com.universalplatform.identity.AuthorizationService;
import com.universalplatform.identity.MembershipDirectory;
import com.universalplatform.identity.PermissionKey;
import com.universalplatform.questionbank.QuestionBankDirectory;
import com.universalplatform.security.ActorContext;
import com.universalplatform.security.TenantContext;
import java.time.Clock; import java.time.Instant; import java.util.*;
import org.springframework.data.domain.PageRequest; import org.springframework.data.domain.Sort; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class AssessmentService implements AssessmentReadDirectory {
 private final TenantContext tenantContext; private final ActorContext actorContext; private final AuthorizationService auth; private final MembershipDirectory memberships; private final EnrollmentDirectory enrollment; private final QuestionBankDirectory questionBank; private final AssessmentRepository assessments; private final AssessmentVersionRepository versions; private final AssessmentQuestionRepository questions; private final AssessmentBatchRepository batches; private final AttemptRepository attempts; private final AnswerRepository answers; private final AuditService audit; private final Clock clock=Clock.systemUTC();
 AssessmentService(TenantContext tenantContext,ActorContext actorContext,AuthorizationService auth,MembershipDirectory memberships,EnrollmentDirectory enrollment,QuestionBankDirectory questionBank,AssessmentRepository assessments,AssessmentVersionRepository versions,AssessmentQuestionRepository questions,AssessmentBatchRepository batches,AttemptRepository attempts,AnswerRepository answers,AuditService audit){this.tenantContext=tenantContext;this.actorContext=actorContext;this.auth=auth;this.memberships=memberships;this.enrollment=enrollment;this.questionBank=questionBank;this.assessments=assessments;this.versions=versions;this.questions=questions;this.batches=batches;this.attempts=attempts;this.answers=answers;this.audit=audit;}
 @Transactional(readOnly=true) public PageResult<AssessmentView> list(int page,int size){auth.require(PermissionKey.ASSESSMENTS_VIEW);var p=assessments.findAllByTenantId(tenantContext.requireTenantId(),PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100),Sort.by(Sort.Direction.DESC,"createdAt","id")));return new PageResult<>(p.getContent().stream().map(this::view).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @Transactional public AssessmentView create(String title){auth.require(PermissionKey.ASSESSMENTS_MANAGE);UUID tid=tenantContext.requireTenantId();Instant now=clock.instant();Assessment a=assessments.save(new Assessment(UUID.randomUUID(),tid,title.trim(),now));audit.record(tid,actorContext.requireSubject(),"ASSESSMENT_CREATED","assessment",a.id().toString());return view(a);}
 @Transactional public AssessmentVersionView createVersion(UUID assessmentId,VersionCommand c){auth.require(PermissionKey.ASSESSMENTS_MANAGE);UUID tid=tenantContext.requireTenantId();Assessment a=requireAssessment(tid,assessmentId);if(a.status()==AssessmentStatus.PUBLISHED)throw new IllegalStateException("Published assessments require a new assessment version before editing");validateWindow(c.availableFrom(),c.availableUntil());if(c.durationSeconds()!=null&&c.durationSeconds()<30)throw new IllegalArgumentException("Duration must be at least 30 seconds");if(c.maxAttempts()<1)throw new IllegalArgumentException("At least one attempt is required");if(c.totalMarks()<1||c.passMarks()<0||c.passMarks()>c.totalMarks())throw new IllegalArgumentException("Invalid marks configuration");int next=versions.findTopByTenantIdAndAssessmentIdOrderByVersionNumberDesc(tid,assessmentId).map(v->v.versionNumber()+1).orElse(1);var v=versions.save(new AssessmentVersion(UUID.randomUUID(),tid,assessmentId,next,c.durationSeconds(),c.maxAttempts(),c.totalMarks(),c.passMarks(),c.shuffleQuestions(),c.allowBacktracking(),c.availableFrom(),c.availableUntil(),c.settingsJson(),clock.instant()));audit.record(tid,actorContext.requireSubject(),"ASSESSMENT_VERSION_CREATED","assessment",assessmentId.toString());return versionView(v);}
 @Transactional(readOnly=true) public List<AssessmentVersionView> versions(UUID assessmentId){auth.require(PermissionKey.ASSESSMENTS_VIEW);UUID tid=tenantContext.requireTenantId();requireAssessment(tid,assessmentId);return versions.findAllByTenantIdAndAssessmentIdOrderByVersionNumberDesc(tid,assessmentId).stream().map(this::versionView).toList();}
 @Transactional(readOnly=true) public AssessmentPacket packet(UUID assessmentVersionId){auth.require(PermissionKey.ASSESSMENTS_VIEW);UUID tid=tenantContext.requireTenantId();var v=versions.findByTenantIdAndId(tid,assessmentVersionId).orElseThrow(()->new IllegalArgumentException("Assessment version not found"));List<PacketQuestion> items=questions.findAllByTenantIdAndAssessmentVersionIdOrderByOrdinalAsc(tid,assessmentVersionId).stream().map(q->{var ref=questionBank.requireQuestionVersion(q.questionVersionId());return new PacketQuestion(q.id(),q.ordinal(),q.marks(),ref.questionVersionId(),ref.type(),ref.title(),ref.difficulty(),ref.payloadJson());}).toList();return new AssessmentPacket(versionView(v),items);}
 @Transactional public AssessmentVersionView addQuestion(UUID assessmentVersionId,UUID questionVersionId,int ordinal){auth.require(PermissionKey.ASSESSMENTS_MANAGE);UUID tid=tenantContext.requireTenantId();var v=versions.findByTenantIdAndId(tid,assessmentVersionId).orElseThrow(()->new IllegalArgumentException("Assessment version not found"));if(v.versionNumber()<1)throw new IllegalStateException("Invalid assessment version");var q=questionBank.requireQuestionVersion(questionVersionId);if(questions.existsByTenantIdAndAssessmentVersionIdAndQuestionVersionId(tid,assessmentVersionId,questionVersionId))throw new IllegalArgumentException("Question version already attached");if(ordinal<1)throw new IllegalArgumentException("Ordinal must be positive");questions.save(new AssessmentQuestion(UUID.randomUUID(),tid,assessmentVersionId,q.questionVersionId(),ordinal,q.positiveMarks()));return versionView(v);}
 @Transactional public AssessmentView publish(UUID assessmentId,long expectedVersion){auth.require(PermissionKey.ASSESSMENTS_MANAGE);UUID tid=tenantContext.requireTenantId();Assessment a=requireAssessment(tid,assessmentId);if(a.version()!=expectedVersion)throw new IllegalStateException("Assessment was modified by another request");var v=versions.findTopByTenantIdAndAssessmentIdOrderByVersionNumberDesc(tid,assessmentId).orElseThrow(()->new IllegalStateException("Assessment version is required"));if(questions.findAllByTenantIdAndAssessmentVersionIdOrderByOrdinalAsc(tid,v.id()).isEmpty())throw new IllegalStateException("Published assessment requires at least one question");a.publish(clock.instant());audit.record(tid,actorContext.requireSubject(),"ASSESSMENT_PUBLISHED","assessment",assessmentId.toString());return view(a);}
 @Transactional public AssignmentView assignBatch(UUID assessmentVersionId,UUID batchId){auth.require(PermissionKey.ASSESSMENTS_MANAGE);UUID tid=tenantContext.requireTenantId();var v=versions.findByTenantIdAndId(tid,assessmentVersionId).orElseThrow(()->new IllegalArgumentException("Assessment version not found"));enrollment.requireBatch(batchId);if(batches.existsByTenantIdAndAssessmentVersionIdAndBatchId(tid,assessmentVersionId,batchId))return new AssignmentView(assessmentVersionId,batchId);batches.save(new AssessmentBatch(UUID.randomUUID(),tid,assessmentVersionId,batchId,clock.instant()));audit.record(tid,actorContext.requireSubject(),"ASSESSMENT_BATCH_ASSIGNED","assessment_version",assessmentVersionId.toString());return new AssignmentView(assessmentVersionId,batchId);}
 @Transactional public AttemptView start(UUID assessmentVersionId){auth.require(PermissionKey.ASSESSMENTS_TAKE);UUID tid=tenantContext.requireTenantId();MembershipDirectory.MembershipReference m=memberships.current();var v=versions.findByTenantIdAndId(tid,assessmentVersionId).orElseThrow(()->new IllegalArgumentException("Assessment version not found"));var assessment=requireAssessment(tid,v.assessmentId());if(assessment.status()!=AssessmentStatus.PUBLISHED)throw new IllegalStateException("Assessment is not published");Instant now=clock.instant();if(now.isBefore(v.availableFrom())||now.isAfter(v.availableUntil()))throw new IllegalStateException("Assessment is outside its availability window");List<UUID> assignedBatches=batches.findAllByTenantIdAndAssessmentVersionId(tid,assessmentVersionId).stream().map(AssessmentBatch::batchId).toList();if(!assignedBatches.isEmpty()){boolean visible=assignedBatches.stream().anyMatch(batchId->enrollment.activeMembershipIdsForBatch(batchId).contains(m.membershipId()));if(!visible)throw new SecurityException("Assessment is not assigned to the current user");}else if(!auth.has(PermissionKey.ASSESSMENTS_MANAGE))throw new SecurityException("Assessment is not assigned to a batch");long previous=attempts.countByTenantIdAndAssessmentVersionIdAndMembershipId(tid,assessmentVersionId,m.membershipId());if(previous>=v.maxAttempts())throw new IllegalStateException("Attempt limit reached");Instant expiry=now.plusSeconds(v.durationSeconds()==null?3600:v.durationSeconds());if(expiry.isAfter(v.availableUntil()))expiry=v.availableUntil();Attempt a=attempts.save(new Attempt(UUID.randomUUID(),tid,assessmentVersionId,m.membershipId(),now,expiry,(int)previous+1));audit.record(tid,actorContext.requireSubject(),"ASSESSMENT_ATTEMPT_STARTED","attempt",a.id().toString());return attemptView(a,v);}
 @Transactional public AnswerView autosave(UUID attemptId,UUID assessmentQuestionId,String payload,String idempotencyKey,long clientSequence){auth.require(PermissionKey.ASSESSMENTS_TAKE);UUID tid=tenantContext.requireTenantId();Attempt a=requireAttempt(tid,attemptId);ensureAttemptOpen(a);if(idempotencyKey==null||idempotencyKey.isBlank())throw new IllegalArgumentException("Idempotency key is required");var existing=answers.findByTenantIdAndIdempotencyKey(tid,idempotencyKey);if(existing.isPresent())return answerView(existing.get());var prior=answers.findByTenantIdAndAttemptIdAndAssessmentQuestionId(tid,attemptId,assessmentQuestionId);long latest=answers.findTopByTenantIdAndAttemptIdOrderByServerSequenceDesc(tid,attemptId).map(Answer::serverSequence).orElse(0L);long sequence=Math.max(latest+1,clientSequence);if(prior.isPresent()){if(sequence<=prior.get().serverSequence())return answerView(prior.get());prior.get().update(payload,sequence,clock.instant());return answerView(prior.get());}var q=questions.findAllByTenantIdAndAssessmentVersionIdOrderByOrdinalAsc(tid,a.assessmentVersionId()).stream().filter(x->x.id().equals(assessmentQuestionId)).findFirst().orElseThrow(()->new IllegalArgumentException("Assessment question not found"));var saved=answers.save(new Answer(UUID.randomUUID(),tid,attemptId,q.id(),payload,sequence,idempotencyKey,clock.instant()));return answerView(saved);}
 @Transactional public AttemptView submit(UUID attemptId){auth.require(PermissionKey.ASSESSMENTS_TAKE);UUID tid=tenantContext.requireTenantId();Attempt a=requireAttempt(tid,attemptId);ensureAttemptOpen(a);Instant now=clock.instant();a.submit(now,now.isAfter(a.expiresAt())?AttemptStatus.EXPIRED:AttemptStatus.SUBMITTED);audit.record(tid,actorContext.requireSubject(),"ASSESSMENT_ATTEMPT_SUBMITTED","attempt",attemptId.toString());var v=versions.findByTenantIdAndId(tid,a.assessmentVersionId()).orElseThrow();return attemptView(a,v);}
 @Transactional(readOnly=true) public AttemptView getAttempt(UUID attemptId){auth.require(PermissionKey.ASSESSMENTS_TAKE);UUID tid=tenantContext.requireTenantId();Attempt a=requireAttempt(tid,attemptId);var v=versions.findByTenantIdAndId(tid,a.assessmentVersionId()).orElseThrow();return attemptView(a,v);}
 private Assessment requireAssessment(UUID t,UUID id){return assessments.findByTenantIdAndId(t,id).orElseThrow(()->new IllegalArgumentException("Assessment not found"));} private Attempt requireAttempt(UUID t,UUID id){Attempt a=attempts.findByTenantIdAndId(t,id).orElseThrow(()->new IllegalArgumentException("Attempt not found"));if(!a.membershipId().equals(memberships.current().membershipId())&&!auth.has(PermissionKey.ASSESSMENTS_MANAGE))throw new SecurityException("Attempt is not visible to the current user");return a;}
 private void ensureAttemptOpen(Attempt a){Instant now=clock.instant();if(a.status()!=AttemptStatus.IN_PROGRESS)throw new IllegalStateException("Attempt is no longer writable");if(now.isAfter(a.expiresAt())){a.submit(now,AttemptStatus.EXPIRED);throw new IllegalStateException("Assessment attempt has expired");}}
 private AssessmentView view(Assessment a){return new AssessmentView(a.id(),a.title(),a.status(),a.version());} private AssessmentVersionView versionView(AssessmentVersion v){return new AssessmentVersionView(v.id(),v.assessmentId(),v.versionNumber(),v.durationSeconds(),v.maxAttempts(),v.totalMarks(),v.passMarks(),v.shuffleQuestions(),v.allowBacktracking(),v.availableFrom(),v.availableUntil());} private AttemptView attemptView(Attempt a,AssessmentVersion v){return new AttemptView(a.id(),a.assessmentVersionId(),a.attemptNumber(),a.status(),a.startedAt(),a.expiresAt(),a.submittedAt(),v.durationSeconds(),v.allowBacktracking());} private AnswerView answerView(Answer a){return new AnswerView(a.id(),a.assessmentQuestionId(),a.serverSequence(),a.savedAt());}
 @Override
 @Transactional(readOnly=true)
 public AssessmentReadDirectory.SubmittedAttempt requireSubmittedAttempt(UUID tenantId, UUID attemptId) {
  var a=attempts.findByTenantIdAndId(tenantId,attemptId).orElseThrow(()->new IllegalArgumentException("Attempt not found"));
  var v=versions.findByTenantIdAndId(tenantId,a.assessmentVersionId()).orElseThrow(()->new IllegalArgumentException("Assessment version not found"));
  boolean submitted=a.status()==AttemptStatus.SUBMITTED||a.status()==AttemptStatus.EXPIRED;
  return new AssessmentReadDirectory.SubmittedAttempt(a.id(),a.membershipId(),v.totalMarks(),v.passMarks(),submitted);
 }
 @Override
 @Transactional(readOnly=true)
 public boolean attemptBelongsToMembership(UUID tenantId, UUID attemptId, UUID membershipId) { return attempts.findByTenantIdAndId(tenantId,attemptId).map(a->a.membershipId().equals(membershipId)).orElse(false); }
 @Override
 @Transactional(readOnly=true)
 public AssessmentReadDirectory.AnswerSnapshot answerById(UUID tenantId, UUID answerId) {
  var x=answers.findByTenantIdAndId(tenantId,answerId).orElseThrow(()->new IllegalArgumentException("Answer not found"));
  var a=attempts.findByTenantIdAndId(tenantId,x.attemptId()).orElseThrow(()->new IllegalArgumentException("Attempt not found"));
  var q=questions.findByTenantIdAndId(tenantId,x.assessmentQuestionId()).orElseThrow(()->new IllegalArgumentException("Assessment question not found"));
  var ref=questionBank.requireQuestionVersion(q.questionVersionId());
  return new AssessmentReadDirectory.AnswerSnapshot(x.id(),a.id(),q.id(),ref.type(),x.payloadJson(),ref.payloadJson(),q.marks(),ref.negativeMarks());
 }
 @Override
 @Transactional(readOnly=true)
 public List<AssessmentReadDirectory.AnswerSnapshot> answersForAttempt(UUID tenantId, UUID attemptId) {
  attempts.findByTenantIdAndId(tenantId,attemptId).orElseThrow(()->new IllegalArgumentException("Attempt not found"));
  return answers.findAllByTenantIdAndAttemptIdOrderByServerSequenceAsc(tenantId,attemptId).stream().map(x->answerById(tenantId,x.id())).toList();
 }

 private static void validateWindow(Instant from,Instant until){if(from==null||until==null||!from.isBefore(until))throw new IllegalArgumentException("Assessment availability window is invalid");}
 @Transactional(readOnly=true)
 public PageResult<AttemptAdminView> listAttempts(UUID assessmentVersionId,int page,int size){auth.require(PermissionKey.ASSESSMENTS_MANAGE);UUID tid=tenantContext.requireTenantId();versions.findByTenantIdAndId(tid,assessmentVersionId).orElseThrow(()->new IllegalArgumentException("Assessment version not found"));var p=attempts.findAllByTenantIdAndAssessmentVersionId(tid,assessmentVersionId,PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100),Sort.by(Sort.Direction.DESC,"startedAt","id")));return new PageResult<>(p.getContent().stream().map(this::adminAttemptView).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @Transactional(readOnly=true)
 public PageResult<AttemptAdminView> listMyAttempts(int page,int size){auth.require(PermissionKey.ASSESSMENTS_TAKE);UUID tid=tenantContext.requireTenantId();var m=memberships.current();var p=attempts.findAllByTenantIdAndMembershipId(tid,m.membershipId(),PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100),Sort.by(Sort.Direction.DESC,"startedAt","id")));return new PageResult<>(p.getContent().stream().map(this::adminAttemptView).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 private AttemptAdminView adminAttemptView(Attempt a){return new AttemptAdminView(a.id(),a.assessmentVersionId(),a.membershipId(),a.attemptNumber(),a.status(),a.startedAt(),a.expiresAt(),a.submittedAt());}
 public record AttemptAdminView(UUID id,UUID assessmentVersionId,UUID membershipId,int attemptNumber,AttemptStatus status,Instant startedAt,Instant expiresAt,Instant submittedAt){}
 public record PageResult<T>(List<T> items,int page,int size,long totalElements,int totalPages){} public record AssessmentView(UUID id,String title,AssessmentStatus status,long version){} public record AssessmentVersionView(UUID id,UUID assessmentId,int versionNumber,Integer durationSeconds,Integer maxAttempts,Integer totalMarks,Integer passMarks,boolean shuffleQuestions,boolean allowBacktracking,Instant availableFrom,Instant availableUntil){} public record AssignmentView(UUID assessmentVersionId,UUID batchId){} public record AttemptView(UUID id,UUID assessmentVersionId,int attemptNumber,AttemptStatus status,Instant startedAt,Instant expiresAt,Instant submittedAt,Integer durationSeconds,boolean allowBacktracking){} public record AnswerView(UUID id,UUID assessmentQuestionId,long serverSequence,Instant savedAt){} public record PacketQuestion(UUID id,int ordinal,int marks,UUID questionVersionId,com.universalplatform.questionbank.QuestionType type,String title,String difficulty,String payloadJson){} public record AssessmentPacket(AssessmentVersionView version,List<PacketQuestion> questions){} public record VersionCommand(Integer durationSeconds,int maxAttempts,int totalMarks,int passMarks,boolean shuffleQuestions,boolean allowBacktracking,Instant availableFrom,Instant availableUntil,String settingsJson){}
}
