package com.universalplatform.assessment;

import java.time.Instant; import java.util.*; import org.springframework.data.domain.*; import org.springframework.data.jpa.repository.*; import org.springframework.data.repository.query.Param;

interface AssessmentRepository extends JpaRepository<Assessment,UUID>{ Optional<Assessment> findByTenantIdAndId(UUID tenantId,UUID id); Page<Assessment> findAllByTenantId(UUID tenantId,Pageable pageable); }
interface AssessmentVersionRepository extends JpaRepository<AssessmentVersion,UUID>{ Optional<AssessmentVersion> findByTenantIdAndId(UUID tenantId,UUID id); List<AssessmentVersion> findAllByTenantIdAndAssessmentIdOrderByVersionNumberDesc(UUID tenantId,UUID assessmentId); Optional<AssessmentVersion> findTopByTenantIdAndAssessmentIdOrderByVersionNumberDesc(UUID tenantId,UUID assessmentId); }
interface AssessmentQuestionRepository extends JpaRepository<AssessmentQuestion,UUID>{ Optional<AssessmentQuestion> findByTenantIdAndId(UUID tenantId, UUID id); List<AssessmentQuestion> findAllByTenantIdAndAssessmentVersionIdOrderByOrdinalAsc(UUID tenantId,UUID assessmentVersionId); boolean existsByTenantIdAndAssessmentVersionIdAndQuestionVersionId(UUID tenantId,UUID assessmentVersionId,UUID questionVersionId); }
interface AssessmentBatchRepository extends JpaRepository<AssessmentBatch,UUID>{ boolean existsByTenantIdAndAssessmentVersionIdAndBatchId(UUID tenantId,UUID assessmentVersionId,UUID batchId); List<AssessmentBatch> findAllByTenantIdAndAssessmentVersionId(UUID tenantId,UUID assessmentVersionId); }
interface AttemptRepository extends JpaRepository<Attempt,UUID>{ Page<Attempt> findAllByTenantIdAndAssessmentVersionId(UUID tenantId, UUID assessmentVersionId, Pageable pageable); Page<Attempt> findAllByTenantIdAndMembershipId(UUID tenantId, UUID membershipId, Pageable pageable); Optional<Attempt> findByTenantIdAndId(UUID tenantId,UUID id); long countByTenantIdAndAssessmentVersionIdAndMembershipId(UUID tenantId,UUID assessmentVersionId,UUID membershipId); List<Attempt> findAllByTenantIdAndMembershipIdOrderByStartedAtDesc(UUID tenantId,UUID membershipId); }
interface AnswerRepository extends JpaRepository<Answer,UUID>{ Optional<Answer> findByTenantIdAndId(UUID tenantId, UUID id); Optional<Answer> findByTenantIdAndAttemptIdAndAssessmentQuestionId(UUID tenantId,UUID attemptId,UUID assessmentQuestionId); Optional<Answer> findByTenantIdAndIdempotencyKey(UUID tenantId,String idempotencyKey); List<Answer> findAllByTenantIdAndAttemptIdOrderByServerSequenceAsc(UUID tenantId,UUID attemptId); Optional<Answer> findTopByTenantIdAndAttemptIdOrderByServerSequenceDesc(UUID tenantId,UUID attemptId); }
