import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { CurrentIdentity } from '../platform/api'
import { createCredentialTemplate, createLearningOutcome, createMentorship, createSurvey, fetchCredentialTemplates, fetchLearningOutcomes, fetchMembers, fetchMentoring, fetchSurveys } from '../platform/api'

export function AdvancedAcademicWorkspace({ me }: { me: CurrentIdentity }) {
  const qc = useQueryClient()
  const outcomes = useQuery({ queryKey:['learning-outcomes'], queryFn:fetchLearningOutcomes, enabled:me.permissions.includes('LEARNING_OUTCOMES_VIEW') })
  const templates = useQuery({ queryKey:['credential-templates'], queryFn:fetchCredentialTemplates, enabled:me.permissions.includes('CREDENTIALS_VIEW') })
  const mentoring = useQuery({ queryKey:['mentoring'], queryFn:fetchMentoring, enabled:me.permissions.includes('MENTORING_VIEW') })
  const surveys = useQuery({ queryKey:['surveys'], queryFn:fetchSurveys, enabled:me.permissions.includes('SURVEYS_VIEW') })
  const members = useQuery({ queryKey:['members'], queryFn:fetchMembers, enabled:me.permissions.includes('USERS_VIEW') || me.permissions.includes('MENTORING_MANAGE') })
  const [active,setActive]=useState<'learning'|'credentials'|'mentoring'|'surveys'>('learning')
  const outcomeMutation=useMutation({mutationFn:createLearningOutcome,onSuccess:()=>void qc.invalidateQueries({queryKey:['learning-outcomes']})})
  const templateMutation=useMutation({mutationFn:createCredentialTemplate,onSuccess:()=>void qc.invalidateQueries({queryKey:['credential-templates']})})
  const mentorMutation=useMutation({mutationFn:createMentorship,onSuccess:()=>void qc.invalidateQueries({queryKey:['mentoring']})})
  const surveyMutation=useMutation({mutationFn:createSurvey,onSuccess:()=>void qc.invalidateQueries({queryKey:['surveys']})})
  return <div className="content-stack">
    <section className="panel"><div className="chip-row">{(['learning','credentials','mentoring','surveys'] as const).map(x=><button key={x} className={active===x?'primary-button':'text-button'} onClick={()=>setActive(x)}>{x}</button>)}</div></section>
    {active==='learning' && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Learning outcomes</p><h3>Outcome and competency foundation</h3></div></div>{me.permissions.includes('LEARNING_OUTCOMES_MANAGE')&&<form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);outcomeMutation.mutate({code:String(f.get('code')),name:String(f.get('name')),description:String(f.get('description')||'')||undefined});e.currentTarget.reset()}}><label>Code<input name="code" required maxLength={80}/></label><label>Name<input name="name" required maxLength={200}/></label><label>Description<textarea name="description" maxLength={2000}/></label><button className="primary-button">Create outcome</button></form>}{outcomes.data?.map(o=><div className="list-row" key={o.id}><strong>{o.code}</strong><span>{o.name}</span></div>)}</section>}
    {active==='credentials' && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Credentials</p><h3>Certificate templates</h3></div></div>{me.permissions.includes('CREDENTIALS_MANAGE')&&<form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);templateMutation.mutate({code:String(f.get('code')),name:String(f.get('name')),credentialType:String(f.get('type')),description:String(f.get('description')||'')||undefined});e.currentTarget.reset()}}><label>Code<input name="code" required maxLength={80}/></label><label>Name<input name="name" required maxLength={200}/></label><label>Type<input name="type" required placeholder="COMPLETION"/></label><label>Description<textarea name="description" maxLength={2000}/></label><button className="primary-button">Create template</button></form>}{templates.data?.map(t=><div className="list-row" key={t.id}><strong>{t.code}</strong><span>{t.name} · {t.credentialType}</span></div>)}</section>}
    {active==='mentoring' && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Mentoring</p><h3>Mentor relationships</h3></div></div>{me.permissions.includes('MENTORING_MANAGE')&&<form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mentorMutation.mutate({mentorMembershipId:String(f.get('mentor')),menteeMembershipId:String(f.get('mentee')),goal:String(f.get('goal'))});e.currentTarget.reset()}}><label>Mentor<select name="mentor" required>{members.data?.items.map(m=><option value={m.membershipId} key={m.membershipId}>{m.displayName}</option>)}</select></label><label>Mentee<select name="mentee" required>{members.data?.items.map(m=><option value={m.membershipId} key={m.membershipId}>{m.displayName}</option>)}</select></label><label>Goal<textarea name="goal" required maxLength={2000}/></label><button className="primary-button">Create mentorship</button></form>}{mentoring.data?.map(m=><div className="list-row" key={m.id}><strong>{m.status}</strong><span>{m.goal}</span></div>)}</section>}
    {active==='surveys' && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Surveys and feedback</p><h3>Institutional feedback</h3></div></div>{me.permissions.includes('SURVEYS_MANAGE')&&<form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);surveyMutation.mutate({title:String(f.get('title')),description:String(f.get('description')||'')||undefined,anonymous:f.get('anonymous')==='on'});e.currentTarget.reset()}}><label>Title<input name="title" required maxLength={240}/></label><label>Description<textarea name="description" maxLength={4000}/></label><label><input name="anonymous" type="checkbox"/> Anonymous responses</label><button className="primary-button">Create survey</button></form>}{surveys.data?.map(s=><div className="list-row" key={s.id}><strong>{s.status}</strong><span>{s.title} · {s.anonymous?'anonymous':'identified'}</span></div>)}</section>}
  </div>
}
