package com.universalplatform.gradebook;
import com.universalplatform.assignment.*; import com.universalplatform.enrollment.EnrollmentDirectory; import com.universalplatform.identity.*; import com.universalplatform.security.TenantContext; import java.math.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service class GradebookService {
 private final TenantContext tenant; private final AuthorizationService auth; private final MembershipDirectory memberships; private final EnrollmentDirectory enrollment; private final AssignmentDirectory assignments;
 GradebookService(TenantContext t,AuthorizationService a,MembershipDirectory m,EnrollmentDirectory e,AssignmentDirectory assignments){tenant=t;auth=a;memberships=m;enrollment=e;this.assignments=assignments;}
 @Transactional(readOnly=true) GradebookView myBatch(UUID batchId){auth.require(PermissionKey.GRADEBOOK_VIEW);UUID mid=memberships.current().membershipId();if(!enrollment.activeBatchIdsForMembership(mid).contains(batchId))throw new SecurityException("Batch is not visible to current user");return build(batchId,mid);}
 @Transactional(readOnly=true) GradebookView learner(UUID batchId,UUID membershipId){auth.require(PermissionKey.GRADEBOOK_VIEW);if(!enrollment.activeBatchIdsForMembership(membershipId).contains(batchId))throw new SecurityException("Learner is not enrolled in batch");return build(batchId,membershipId);}
 private GradebookView build(UUID batchId,UUID membershipId){List<AssignmentDirectory.GradebookAssignment> raw=assignments.gradebookAssignments(batchId,membershipId);List<GradebookEntry> entries=raw.stream().map(x->new GradebookEntry(x.assignmentId(),x.title(),x.maxPoints(),x.weightBasisPoints(),x.awardedPoints(),x.status())).toList();List<GradebookFormula.GradeEntry> calc=raw.stream().map(x->new GradebookFormula.GradeEntry(x.maxPoints(),x.weightBasisPoints(),x.awardedPoints())).toList();var f=GradebookFormula.compute(calc);return new GradebookView(batchId,membershipId,f.weightedPoints(),f.completedAssignments(),f.totalAssignments(),entries);}
 public record GradebookView(UUID batchId,UUID membershipId,BigDecimal weightedPoints,int completedAssignments,int totalAssignments,List<GradebookEntry> entries){}
 public record GradebookEntry(UUID assignmentId,String title,int maxPoints,int weightBasisPoints,Integer awardedPoints,AssignmentStatus status){}
}
