package com.universalplatform.notification;

public enum NotificationEventType {
    CLASS_SCHEDULED,
    CLASS_RESCHEDULED,
    CLASS_CANCELLED,
    CLASS_STARTING,
    EXAM_SCHEDULED,
    EXAM_RESCHEDULED,
    EXAM_CANCELLED,
    EXAM_STARTING,
    SCHEDULED,
    SCHEDULE_RESCHEDULED,
    SCHEDULE_CANCELLED,
    ANNOUNCEMENT_PUBLISHED,
    RESOURCE_RELEASED,
    ASSIGNMENT_DUE,
    RESULT_PUBLISHED,
    RECORDING_READY,
    PAYMENT_DUE,
    CHALLENGE_UPDATED
}
