package com.universalplatform.finance;

import com.universalplatform.audit.AuditService;
import com.universalplatform.identity.AuthorizationService;
import com.universalplatform.identity.PermissionKey;
import com.universalplatform.identity.MembershipDirectory;
import com.universalplatform.licensing.EntitlementService;
import com.universalplatform.security.ActorContext;
import com.universalplatform.security.TenantContext;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.*;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
class FinanceService {
 private final TenantContext tenants; private final ActorContext actors; private final AuthorizationService auth; private final MembershipDirectory memberships; private final EntitlementService entitlements;
 private final InstitutionFeeRepository fees; private final InvoiceRepository invoices; private final InstallmentRepository installments; private final PaymentRepository payments; private final ReceiptRepository receipts; private final AuditService audit; private final PaymentProvider provider; private final Clock clock=Clock.systemUTC();
 FinanceService(TenantContext tenants,ActorContext actors,AuthorizationService auth,MembershipDirectory memberships,EntitlementService entitlements,InstitutionFeeRepository fees,InvoiceRepository invoices,InstallmentRepository installments,PaymentRepository payments,ReceiptRepository receipts,AuditService audit,PaymentProvider provider){this.tenants=tenants;this.actors=actors;this.auth=auth;this.memberships=memberships;this.entitlements=entitlements;this.fees=fees;this.invoices=invoices;this.installments=installments;this.payments=payments;this.receipts=receipts;this.audit=audit;this.provider=provider;}
 @Transactional(readOnly=true) List<FeeView> listFees(){auth.require(PermissionKey.FINANCE_VIEW);UUID t=tenants.requireTenantId();return fees.findAllByTenantIdOrderByName(t).stream().map(this::fee).toList();}
 @Transactional FeeView upsertFee(UUID id,String name,BigDecimal amount,String currency,FeeStatus status,long expectedVersion){auth.require(PermissionKey.FINANCE_MANAGE);UUID t=tenants.requireTenantId();validateMoney(amount,currency);InstitutionFee f=id==null?new InstitutionFee(UUID.randomUUID(),t,name.trim(),amount.setScale(2,RoundingMode.HALF_UP),currency.toUpperCase(Locale.ROOT),clock.instant()):fees.findByTenantIdAndId(t,id).orElseThrow();if(id!=null&&f.version()!=expectedVersion)throw new IllegalStateException("Fee was modified");f.update(name.trim(),amount.setScale(2,RoundingMode.HALF_UP),currency.toUpperCase(Locale.ROOT),status);fees.save(f);audit.record(t,actors.requireSubject(),id==null?"FEE_CREATED":"FEE_UPDATED","institution-fee",f.id().toString());return fee(f);}
 @Transactional InvoiceView createInvoice(UUID membershipId,BigDecimal total,String currency,LocalDate dueOn,List<InstallmentRequest> parts){auth.require(PermissionKey.FINANCE_MANAGE);UUID t=tenants.requireTenantId();memberships.requireActive(membershipId);validateMoney(total,currency);if(dueOn==null)throw new IllegalArgumentException("dueOn is required");BigDecimal normalized=total.setScale(2,RoundingMode.HALF_UP);String number="INV-"+DateTimeFormatterHolder.today(clock)+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT);Invoice i=invoices.save(new Invoice(UUID.randomUUID(),t,membershipId,number,normalized,currency.toUpperCase(Locale.ROOT),dueOn,clock.instant()));if(parts!=null&&!parts.isEmpty()){BigDecimal sum=BigDecimal.ZERO;int seq=1;for(InstallmentRequest p:parts){if(p.amount()==null||p.amount().signum()<=0||p.dueOn()==null)throw new IllegalArgumentException("Invalid installment");sum=sum.add(p.amount().setScale(2,RoundingMode.HALF_UP));installments.save(new Installment(UUID.randomUUID(),t,i.id(),seq++,p.amount().setScale(2,RoundingMode.HALF_UP),p.dueOn()));}if(sum.compareTo(normalized)!=0)throw new IllegalArgumentException("Installments must equal invoice total");}audit.record(t,actors.requireSubject(),"INVOICE_CREATED","invoice",i.id().toString());return invoice(i);}
 @Transactional InvoiceView issue(UUID id,long expectedVersion){auth.require(PermissionKey.FINANCE_MANAGE);Invoice i=require(id);if(i.version()!=expectedVersion)throw new IllegalStateException("Invoice was modified");i.issue(LocalDate.now(clock));audit.record(i.tenantId(),actors.requireSubject(),"INVOICE_ISSUED","invoice",i.id().toString());return invoice(i);}
 @Transactional PaymentView pay(UUID invoiceId,BigDecimal amount,String currency){auth.require(PermissionKey.FINANCE_MANAGE);Invoice i=require(invoiceId);if(i.status()==InvoiceStatus.DRAFT||i.status()==InvoiceStatus.VOID||i.status()==InvoiceStatus.PAID)throw new IllegalStateException("Invoice is not payable");if(!i.currency().equalsIgnoreCase(currency))throw new IllegalArgumentException("Payment currency does not match invoice");if(amount==null||amount.signum()<=0||i.paidAmount().add(amount).compareTo(i.totalAmount())>0)throw new IllegalArgumentException("Invalid payment amount");if(!entitlements.decide(i.tenantId(),com.universalplatform.licensing.FeatureKey.PAYMENTS).allowed())throw new IllegalStateException("PAYMENTS feature is not entitled");Payment p=payments.save(new Payment(UUID.randomUUID(),i.tenantId(),i.id(),i.membershipId(),amount.setScale(2,RoundingMode.HALF_UP),currency.toUpperCase(Locale.ROOT),provider.name(),clock.instant()));var authz=provider.authorize(p.id(),p.amount(),p.currency());if(!authz.success()){p.fail(authz.message());throw new IllegalStateException("Payment authorization failed");}p.authorize(authz.reference());var captured=provider.capture(p.providerReference());if(!captured.success()){p.fail(captured.message());throw new IllegalStateException("Payment capture failed");}p.capture(clock.instant());i.applyPayment(p.amount(),LocalDate.now(clock));payments.save(p);invoices.save(i);Receipt r=receipts.save(new Receipt(UUID.randomUUID(),i.tenantId(),p.id(),"RCT-"+p.id().toString().substring(0,12).toUpperCase(Locale.ROOT),p.amount(),p.currency(),clock.instant()));audit.record(i.tenantId(),actors.requireSubject(),"PAYMENT_CAPTURED","payment",p.id().toString());return payment(p,r);}
 @Transactional(readOnly=true) PageView<InvoiceView> listInvoices(int page,int size){auth.require(PermissionKey.FINANCE_VIEW);UUID t=tenants.requireTenantId();var p=invoices.findAllByTenantIdOrderByCreatedAtDesc(t,org.springframework.data.domain.PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size))));return new PageView<>(p.getContent().stream().map(this::invoice).toList(),p.getNumber(),p.getSize(),p.getTotalElements());}
 @Transactional(readOnly=true) InvoiceView getInvoice(UUID id){auth.require(PermissionKey.FINANCE_VIEW);return invoice(require(id));}
 private Invoice require(UUID id){return invoices.findByTenantIdAndId(tenants.requireTenantId(),id).orElseThrow(()->new IllegalArgumentException("Invoice not found"));}
 private FeeView fee(InstitutionFee f){return new FeeView(f.id(),f.name(),f.amount(),f.currency(),f.status(),f.version());}
 private InvoiceView invoice(Invoice i){return new InvoiceView(i.id(),i.membershipId(),i.invoiceNumber(),i.totalAmount(),i.paidAmount(),i.currency(),i.status(),i.issuedOn(),i.dueOn(),i.version(),installments.findAllByTenantIdAndInvoiceIdOrderBySequenceNo(i.tenantId(),i.id()).stream().map(x->new InstallmentView(x.id(),x.sequenceNo(),x.amount(),x.dueOn(),x.status(),x.version())).toList());}
 private PaymentView payment(Payment p,Receipt r){return new PaymentView(p.id(),p.invoiceId(),p.amount(),p.currency(),p.provider(),p.providerReference(),p.status(),p.capturedAt(),new ReceiptView(r.id(),r.receiptNumber(),r.amount(),r.currency(),r.issuedAt()));}
 private static void validateMoney(BigDecimal amount,String currency){if(amount==null||amount.signum()<0||amount.scale()>2)throw new IllegalArgumentException("Amount must be non-negative with at most two decimal places");if(currency==null||!currency.matches("[A-Za-z]{3}"))throw new IllegalArgumentException("Currency must be ISO-4217 alphabetic code");}
 record InstallmentRequest(BigDecimal amount,LocalDate dueOn){} record FeeView(UUID id,String name,BigDecimal amount,String currency,FeeStatus status,long version){} record InstallmentView(UUID id,int sequenceNo,BigDecimal amount,LocalDate dueOn,InstallmentStatus status,long version){} record InvoiceView(UUID id,UUID membershipId,String invoiceNumber,BigDecimal totalAmount,BigDecimal paidAmount,String currency,InvoiceStatus status,LocalDate issuedOn,LocalDate dueOn,long version,List<InstallmentView> installments){} record PaymentView(UUID id,UUID invoiceId,BigDecimal amount,String currency,String provider,String providerReference,PaymentStatus status,Instant capturedAt,ReceiptView receipt){} record ReceiptView(UUID id,String receiptNumber,BigDecimal amount,String currency,Instant issuedAt){} record PageView<T>(List<T> items,int page,int size,long totalElements){}
 static final class DateTimeFormatterHolder{static String today(Clock c){return LocalDate.now(c).toString().replace("-","");}}
}
