package com.universalplatform.liveclass;

import com.universalplatform.audit.AuditService; import com.universalplatform.enrollment.EnrollmentDirectory; import com.universalplatform.identity.*; import com.universalplatform.scheduling.ScheduleDirectory; import com.universalplatform.security.*;
import java.time.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service class LiveClassService implements LiveClassDirectory {
 private final TenantContext tenant; private final ActorContext actor; private final AuthorizationService auth; private final MembershipDirectory memberships; private final EnrollmentDirectory enrollment; private final ScheduleDirectory schedules; private final LiveClassRepository liveClasses; private final LiveClassParticipantRepository participants; private final LiveMediaProvider mediaProvider; private final AuditService audit; private final Clock clock=Clock.systemUTC();
 LiveClassService(TenantContext tenant,ActorContext actor,AuthorizationService auth,MembershipDirectory memberships,EnrollmentDirectory enrollment,ScheduleDirectory schedules,LiveClassRepository liveClasses,LiveClassParticipantRepository participants,LiveMediaProvider mediaProvider,AuditService audit){this.tenant=tenant;this.actor=actor;this.auth=auth;this.memberships=memberships;this.enrollment=enrollment;this.schedules=schedules;this.liveClasses=liveClasses;this.participants=participants;this.mediaProvider=mediaProvider;this.audit=audit;}
 @Transactional LiveClassView create(UUID classSessionId,AttendancePolicy policy,Integer minimumAttendanceSeconds,Integer attendanceThresholdBasisPoints,boolean lowBandwidth,boolean chatEnabled){auth.require(PermissionKey.LIVE_CLASS_MANAGE);UUID tid=tenant.requireTenantId();var session=schedules.requireClassSession(classSessionId);if("CANCELLED".equals(session.lifecycleStatus()))throw new IllegalStateException("Cannot create a live class for a cancelled class session");if(session.batchId()==null)throw new IllegalArgumentException("Live classes currently require a batch-backed class session");if(liveClasses.findByTenantIdAndClassSessionId(tid,classSessionId).isPresent())throw new IllegalStateException("Live class already exists");if(minimumAttendanceSeconds==null)minimumAttendanceSeconds=0;if(minimumAttendanceSeconds<0||minimumAttendanceSeconds>86400)throw new IllegalArgumentException("Invalid minimum attendance seconds"); if(policy==AttendancePolicy.MINIMUM_DURATION && minimumAttendanceSeconds<1)throw new IllegalArgumentException("Minimum-duration attendance requires at least one second");String room="uep-"+tid+"-"+classSessionId;int threshold = policy==AttendancePolicy.PERCENTAGE ? (attendanceThresholdBasisPoints==null?7500:attendanceThresholdBasisPoints) : 0; if(threshold<0||threshold>10000) throw new IllegalArgumentException("Invalid attendance threshold"); LiveClass lc=liveClasses.save(new LiveClass(UUID.randomUUID(),tid,classSessionId,session.batchId(),room,policy==null?AttendancePolicy.JOIN_TIME:policy,minimumAttendanceSeconds,threshold,lowBandwidth,chatEnabled,clock.instant()));audit.record(tid,actor.requireSubject(),"LIVE_CLASS_CREATED","live_class",lc.id().toString());return view(lc);}
 @Transactional(readOnly=true) PageResult<LiveClassView> list(int page,int size){auth.require(PermissionKey.LIVE_CLASS_VIEW);UUID tid=tenant.requireTenantId();int pg=Math.max(0,page), sz=Math.min(100,Math.max(1,size));Pageable pageable=PageRequest.of(pg,sz,Sort.by(Sort.Direction.ASC,"createdAt","id"));Page<LiveClass> p;if(auth.has(PermissionKey.LIVE_CLASS_MANAGE)){p=liveClasses.findAllByTenantId(tid,pageable);}else{var batchIds=enrollment.activeBatchIdsForMembership(memberships.current().membershipId());p=batchIds.isEmpty()?Page.empty(pageable):liveClasses.findAllByTenantIdAndBatchIdIn(tid,batchIds,pageable);}return new PageResult<>(p.getContent().stream().map(this::view).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @Transactional LiveClassView start(UUID id){auth.require(PermissionKey.LIVE_CLASS_MANAGE);LiveClass lc=require0(id);lc.start(clock.instant());audit.record(tenant.requireTenantId(),actor.requireSubject(),"LIVE_CLASS_STARTED","live_class",id.toString());return view(lc);}
 @Transactional LiveClassView end(UUID id){auth.require(PermissionKey.LIVE_CLASS_MANAGE);LiveClass lc=require0(id);lc.end(clock.instant());audit.record(tenant.requireTenantId(),actor.requireSubject(),"LIVE_CLASS_ENDED","live_class",id.toString());return view(lc);}
 @Transactional TokenView join(UUID id,String clientProfile){auth.require(PermissionKey.LIVE_CLASS_VIEW);UUID tid=tenant.requireTenantId();UUID mid=memberships.current().membershipId();LiveClass lc=require0(id);if(lc.status()!=LiveClassStatus.LIVE)throw new IllegalStateException("Live class is not live");var sessionRef=schedules.requireClassSession(lc.classSessionId());
 if("CANCELLED".equals(sessionRef.status())) throw new IllegalStateException("Live class references a cancelled class session");
 if(sessionRef.batchId()==null) throw new IllegalStateException("Live classes currently require a batch-backed class session");
 Set<UUID> allowed=enrollment.activeMembershipIdsForBatch(sessionRef.batchId()); if(!allowed.contains(mid)) throw new SecurityException("Not an active member of the live class audience");var p=participants.findByTenantIdAndLiveClassIdAndMembershipId(tid,id,mid).orElseGet(()->participants.save(new LiveClassParticipant(UUID.randomUUID(),tid,id,mid,roleFor(mid,lc),clock.instant())));p.join(clock.instant(),clientProfile==null?"BALANCED":clientProfile);boolean publish=p.role()==ParticipantRole.HOST||p.role()==ParticipantRole.MODERATOR||p.role()==ParticipantRole.PRESENTER||auth.has(PermissionKey.LIVE_CLASS_MANAGE);boolean admin=p.role()==ParticipantRole.HOST||p.role()==ParticipantRole.MODERATOR||auth.has(PermissionKey.LIVE_CLASS_MODERATE);String token=mediaProvider.issueToken("m-"+mid,memberships.current().displayName(),lc.roomName(),publish,true,lc.chatEnabled() && auth.has(PermissionKey.LIVE_CLASS_CHAT),admin,3600);audit.record(tid,actor.requireSubject(),"LIVE_CLASS_JOINED","live_class_participant",p.id().toString());return new TokenView(mediaProvider.serverUrl(),token,lc.id(),lc.roomName(),p.role(),lc.lowBandwidth(),lc.chatEnabled());}
 @Transactional void leave(UUID id){auth.require(PermissionKey.LIVE_CLASS_VIEW); leave(id,memberships.current().membershipId());}
 @Transactional @Override public void heartbeat(UUID id,UUID membershipId){UUID tid=tenant.requireTenantId();LiveClassParticipant p=participants.findByTenantIdAndLiveClassIdAndMembershipId(tid,id,membershipId).orElseThrow(()->new IllegalArgumentException("Participant not found"));p.heartbeat(clock.instant());}
 @Transactional @Override public void leave(UUID id,UUID membershipId){UUID tid=tenant.requireTenantId();LiveClassParticipant p=participants.findByTenantIdAndLiveClassIdAndMembershipId(tid,id,membershipId).orElseThrow(()->new IllegalArgumentException("Participant not found"));p.leave(clock.instant());audit.record(tid,actor.requireSubject(),"LIVE_CLASS_LEFT","live_class_participant",p.id().toString());}
 @Transactional void mute(UUID id,UUID membershipId){auth.require(PermissionKey.LIVE_CLASS_MODERATE);LiveClassParticipant p=participant(id,membershipId);p.moderateMute();audit.record(tenant.requireTenantId(),actor.requireSubject(),"LIVE_CLASS_PARTICIPANT_MUTED","live_class_participant",p.id().toString());}
 @Transactional void kick(UUID id,UUID membershipId,String reason){auth.require(PermissionKey.LIVE_CLASS_MODERATE);LiveClassParticipant p=participant(id,membershipId);p.moderateKick(reason==null?"Moderated by host":reason,clock.instant());audit.record(tenant.requireTenantId(),actor.requireSubject(),"LIVE_CLASS_PARTICIPANT_KICKED","live_class_participant",p.id().toString());}
 @Transactional(readOnly=true) PageResult<ParticipantView> participants(UUID id,int page,int size){auth.require(PermissionKey.LIVE_CLASS_MODERATE);UUID tid=tenant.requireTenantId();Page<LiveClassParticipant> p=participants.findAllByTenantIdAndLiveClassId(tid,id,PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.ASC,"invitedAt","id")));return new PageResult<>(p.getContent().stream().map(x->new ParticipantView(x.membershipId(),x.role(),x.status(),x.joinedAt(),x.leftAt(),x.totalPresentSeconds(),x.lastClientProfile(),x.moderationReason(),x.version())).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 private ParticipantRole roleFor(UUID mid,LiveClass lc){if(memberships.current().membershipId().equals(mid)&&auth.has(PermissionKey.LIVE_CLASS_MANAGE))return ParticipantRole.HOST;return ParticipantRole.PARTICIPANT;}
 private LiveClassParticipant participant(UUID id,UUID mid){return participants.findByTenantIdAndLiveClassIdAndMembershipId(tenant.requireTenantId(),id,mid).orElseThrow(()->new IllegalArgumentException("Participant not found"));}
 @Override @Transactional(readOnly=true) public LiveClassReference require(UUID id){LiveClass x=require0(id);return ref(x);}
 @Override @Transactional(readOnly=true) public LiveClassReference requireForClassSession(UUID classSessionId){return ref(liveClasses.findByTenantIdAndClassSessionId(tenant.requireTenantId(),classSessionId).orElseThrow(()->new IllegalArgumentException("Live class not found")));}

 @Override @Transactional(readOnly=true) public List<ParticipantSnapshot> participantSnapshots(UUID id){
  UUID tid=tenant.requireTenantId();
  LiveClass x=require0(id);
  Instant now=clock.instant();
  return participants.findAllByTenantIdAndLiveClassId(tid,id).stream().map(p->{ long seconds=p.totalPresentSeconds(); if(p.joinedAt()!=null&&p.leftAt()==null) seconds+=Math.max(0,Duration.between(p.joinedAt(),now).getSeconds()); return new ParticipantSnapshot(p.membershipId(),p.role(),p.status(),p.joinedAt(),p.leftAt(),seconds,p.lastHeartbeatAt()); }).toList();
 }
 private LiveClass require0(UUID id){return liveClasses.findByTenantIdAndId(tenant.requireTenantId(),id).orElseThrow(()->new IllegalArgumentException("Live class not found"));}
 private LiveClassReference ref(LiveClass x){return new LiveClassReference(x.id(),x.classSessionId(),x.batchId(),x.roomName(),x.status(),x.attendancePolicy(),x.minimumAttendanceSeconds(),x.attendanceThresholdBasisPoints(),x.lowBandwidth(),x.chatEnabled(),x.startedAt(),x.endedAt());}
 private LiveClassView view(LiveClass x){return new LiveClassView(x.id(),x.classSessionId(),x.batchId(),x.roomName(),x.status(),x.attendancePolicy(),x.minimumAttendanceSeconds(),x.attendanceThresholdBasisPoints(),x.lowBandwidth(),x.chatEnabled(),x.startedAt(),x.endedAt(),x.version());}
 record LiveClassView(UUID id,UUID classSessionId,UUID batchId,String roomName,LiveClassStatus status,AttendancePolicy attendancePolicy,int minimumAttendanceSeconds,int attendanceThresholdBasisPoints,boolean lowBandwidth,boolean chatEnabled,Instant startedAt,Instant endedAt,long version){}
 record TokenView(String serverUrl,String participantToken,UUID liveClassId,String roomName,ParticipantRole role,boolean lowBandwidth,boolean chatEnabled){}
 record ParticipantView(UUID membershipId,ParticipantRole role,ParticipantStatus status,Instant joinedAt,Instant leftAt,long totalPresentSeconds,String clientProfile,String moderationReason,long version){}
 record PageResult<T>(List<T> items,int page,int size,long totalElements,int totalPages){}
}
