package com.universalplatform.integration;
import com.universalplatform.identity.*; import com.universalplatform.security.*; import java.nio.charset.StandardCharsets; import java.util.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class OneRosterService implements OneRosterAdapter {
 private final TenantContext tenants; private final AuthorizationService auth; private final JdbcTemplate jdbc;
 OneRosterService(TenantContext t,AuthorizationService a,JdbcTemplate j){tenants=t;auth=a;jdbc=j;}
 @Override @Transactional(readOnly=true) public Map<String,String> exportCsv(){auth.require(PermissionKey.INTEROPERABILITY_VIEW);UUID t=tenants.requireTenantId();Map<String,String> out=new LinkedHashMap<>();out.put("orgs.csv",csv("sourcedId,status,name,type,identifier",jdbc.query("select id, status, display_name, 'school', code from branch where tenant_id=? order by code",(r,n)->List.of(r.getObject(1).toString(),r.getString(2),r.getString(3),r.getString(4),r.getString(5)),t)));out.put("users.csv",csv("sourcedId,status,enabledUser,givenName,foaf_email",jdbc.query("select m.id,m.status, (m.status='ACTIVE'), split_part(u.display_name,' ',1), coalesce(u.email,'') from tenant_membership m join user_account u on u.id=m.user_id where m.tenant_id=? order by m.id",(r,n)->List.of(r.getObject(1).toString(),r.getString(2),String.valueOf(r.getBoolean(3)),r.getString(4),r.getString(5)),t)));out.put("courses.csv",csv("sourcedId,status,title,courseCode",jdbc.query("select id, status, display_name, code from course where tenant_id=? order by code",(r,n)->List.of(r.getObject(1).toString(),r.getString(2),r.getString(3),r.getString(4)),t)));out.put("classes.csv",csv("sourcedId,status,title,classCode,courseSourcedId,locationSourcedId",jdbc.query("select id, status, display_name, code, course_id, branch_id from batch where tenant_id=? order by code",(r,n)->List.of(r.getObject(1).toString(),r.getString(2),r.getString(3),r.getString(4),Objects.toString(r.getObject(5),""),Objects.toString(r.getObject(6),"")),t)));out.put("enrollments.csv",csv("sourcedId,classSourcedId,userSourcedId,role,status,dateLastModified",jdbc.query("select e.id,e.batch_id,e.membership_id, case when exists(select 1 from role_assignment ra join role_definition rd on rd.id=ra.role_id where ra.tenant_id=e.tenant_id and ra.membership_id=e.membership_id and rd.system_key in ('TEACHER','TEACHING_ASSISTANT','MENTOR')) then 'teacher' else 'student' end,e.ended_at is null,e.enrolled_at from enrollment e where e.tenant_id=? and e.batch_id is not null order by e.id",(r,n)->List.of(r.getObject(1).toString(),r.getObject(2).toString(),r.getObject(3).toString(),r.getString(4),r.getBoolean(5)?"active":"tobedeleted",r.getObject(6).toString()),t)));return out;}
 @Override public ImportResult validateCsv(Map<String,String> files){auth.require(PermissionKey.INTEROPERABILITY_MANAGE);if(files==null||files.isEmpty())return new ImportResult(false,0,0,"No OneRoster files supplied");Set<String> required=Set.of("orgs.csv","users.csv","courses.csv","classes.csv","enrollments.csv");if(!files.keySet().containsAll(required))return new ImportResult(false,files.size(),0,"Required OneRoster CSV files are missing");int rows=0;for(String name:required){String text=files.get(name);if(text==null||text.isBlank())return new ImportResult(false,files.size(),rows,name+" is empty");String[] lines=text.replace("\r\n","\n").split("\n",-1);if(lines.length<2)return new ImportResult(false,files.size(),rows,name+" has no data rows");rows+=lines.length-1;}return new ImportResult(true,files.size(),rows,"OneRoster 1.2 CSV envelope validated; persistence mapping is adapter-specific");}
 private static String csv(String header,List<List<String>> rows){StringBuilder b=new StringBuilder(header).append('\n');for(List<String> row:rows){for(int i=0;i<row.size();i++){if(i>0)b.append(',');b.append(escape(row.get(i)));}b.append('\n');}return b.toString();}private static String escape(String v){String x=v==null?"":v;if(x.contains(",")||x.contains("\"")||x.contains("\n"))return "\""+x.replace("\"","\"\"")+"\"";return x;}
}
