package com.universalplatform.assignment;
import jakarta.persistence.*; import java.time.*; import java.util.UUID;
@Entity @Table(name="assignment_submission") class AssignmentSubmission {
 @Id UUID id; @Column(nullable=false) UUID tenantId; @Column(nullable=false) UUID assignmentId; @Column(nullable=false) UUID membershipId; @Column(nullable=false) int attemptNumber;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=20) SubmissionStatus status; @Enumerated(EnumType.STRING) @Column(nullable=false,length=20) SubmissionGradeStatus gradeStatus;
 @Column(columnDefinition="text") String textBody; UUID resourceId; Instant submittedAt; Instant createdAt; Instant updatedAt; Integer awardedPoints; @Column(columnDefinition="text") String graderFeedback; @Column(columnDefinition="text") String rubricScoresJson; @Column(nullable=false) boolean late; @Version @Column(nullable=false) long version;
 protected AssignmentSubmission(){}
 AssignmentSubmission(UUID id,UUID tenantId,UUID assignmentId,UUID membershipId,int attemptNumber,SubmissionStatus status,Instant now,String textBody,UUID resourceId){this.id=id;this.tenantId=tenantId;this.assignmentId=assignmentId;this.membershipId=membershipId;this.attemptNumber=attemptNumber;this.status=status;this.gradeStatus=SubmissionGradeStatus.UNGRADED;this.createdAt=now;this.updatedAt=now;this.textBody=textBody;this.resourceId=resourceId;this.late=false;this.rubricScoresJson="{}";}
 UUID id(){return id;} UUID tenantId(){return tenantId;} UUID assignmentId(){return assignmentId;} UUID membershipId(){return membershipId;} int attemptNumber(){return attemptNumber;} SubmissionStatus status(){return status;} SubmissionGradeStatus gradeStatus(){return gradeStatus;} String textBody(){return textBody;} UUID resourceId(){return resourceId;} Instant submittedAt(){return submittedAt;} Instant createdAt(){return createdAt;} Instant updatedAt(){return updatedAt;} Integer awardedPoints(){return awardedPoints;} String graderFeedback(){return graderFeedback;} String rubricScoresJson(){return rubricScoresJson;} boolean late(){return late;} long version(){return version;}
 void saveDraft(String textBody,UUID resourceId,Instant now){if(status==SubmissionStatus.SUBMITTED||status==SubmissionStatus.RESUBMITTED)throw new IllegalStateException("Submitted work cannot be edited");this.textBody=textBody;this.resourceId=resourceId;this.status=SubmissionStatus.DRAFT;this.updatedAt=now;}
 void submit(Instant now){if((textBody==null||textBody.isBlank())&&resourceId==null)throw new IllegalArgumentException("Submission content is required");this.status=attemptNumber>1?SubmissionStatus.RESUBMITTED:SubmissionStatus.SUBMITTED;this.submittedAt=now;this.updatedAt=now;}
 void markLate(boolean value){this.late=value;}
 void grade(int points,String feedback,String rubricScoresJson,Instant now){this.awardedPoints=points;this.graderFeedback=feedback;this.rubricScoresJson=rubricScoresJson==null?"{}":rubricScoresJson;this.gradeStatus=SubmissionGradeStatus.GRADED;this.updatedAt=now;}
}
