package com.universalplatform.engagement;
import com.universalplatform.audit.AuditService; import com.universalplatform.identity.AuthorizationService; import com.universalplatform.identity.MembershipDirectory; import com.universalplatform.identity.PermissionKey; import com.universalplatform.security.ActorContext; import com.universalplatform.security.TenantContext; import java.time.Clock; import java.time.Instant; import java.util.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service class EngagementService { private final TenantContext tenant; private final ActorContext actor; private final AuthorizationService auth; private final AuditService audit; private final MembershipDirectory memberships; private final JdbcTemplate jdbc; private final Clock clock=Clock.systemUTC(); EngagementService(TenantContext tenant,ActorContext actor,AuthorizationService auth,AuditService audit,MembershipDirectory memberships,JdbcTemplate jdbc){this.tenant=tenant;this.actor=actor;this.auth=auth;this.audit=audit;this.memberships=memberships;this.jdbc=jdbc;}
@Transactional MentorshipView createMentor(UUID mentor,UUID mentee,String goal){auth.require(PermissionKey.MENTORING_MANAGE); UUID t=tenant.requireTenantId(); memberships.requireActive(mentor); memberships.requireActive(mentee); if(mentor.equals(mentee))throw new IllegalArgumentException("Mentor and mentee must differ"); UUID id=UUID.randomUUID(); jdbc.update("insert into mentorship(id,tenant_id,mentor_membership_id,mentee_membership_id,goal,status,created_at) values(?,?,?,?,?,'REQUESTED',?)",id,t,mentor,mentee,goal,clock.instant()); audit.record(t,actor.requireSubject(),"MENTORSHIP_CREATED","mentorship",id.toString()); return mentorship(id);}
@Transactional(readOnly=true) List<MentorshipView> mentoring(){auth.require(PermissionKey.MENTORING_VIEW); UUID t=tenant.requireTenantId(); return jdbc.query("select id,mentor_membership_id,mentee_membership_id,goal,status,created_at,updated_at,version from mentorship where tenant_id=? order by created_at desc",(rs,n)->new MentorshipView(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getObject(3,UUID.class),rs.getString(4),rs.getString(5),rs.getObject(6,Instant.class),rs.getObject(7,Instant.class),rs.getLong(8)),t);}
@Transactional void updateMentor(UUID id,String status,String goal,long expectedVersion){auth.require(PermissionKey.MENTORING_MANAGE); UUID t=tenant.requireTenantId(); MentorshipView m=mentorship(id); if(m.version()!=expectedVersion)throw new IllegalStateException("Mentorship was modified"); if(!Set.of("REQUESTED","ACTIVE","PAUSED","COMPLETED","DECLINED").contains(status))throw new IllegalArgumentException("Invalid mentorship status"); jdbc.update("update mentorship set status=?,goal=?,updated_at=?,version=version+1 where tenant_id=? and id=?",status,goal,clock.instant(),t,id); audit.record(t,actor.requireSubject(),"MENTORSHIP_UPDATED","mentorship",id.toString());}
@Transactional(readOnly=true) List<SurveyView> surveys(){auth.require(PermissionKey.SURVEYS_VIEW); UUID t=tenant.requireTenantId(); return jdbc.query("select id,title,anonymous,opens_at,closes_at,status,version from survey where tenant_id=? order by opens_at desc",(rs,n)->new SurveyView(rs.getObject(1,UUID.class),rs.getString(2),rs.getBoolean(3),rs.getObject(4,Instant.class),rs.getObject(5,Instant.class),rs.getString(6),rs.getLong(7)),t);}
@Transactional SurveyQuestionView addQuestion(UUID surveyId,int sequence,String type,String prompt,boolean required,String optionsJson){auth.require(PermissionKey.SURVEYS_MANAGE); UUID t=tenant.requireTenantId(); surveyForTenant(surveyId); if(sequence<1)throw new IllegalArgumentException("sequence must be positive"); UUID id=UUID.randomUUID(); jdbc.update("insert into survey_question(id,tenant_id,survey_id,sequence_number,question_type,prompt,required,options_json) values(?,?,?,?,?,?,?,cast(? as jsonb))",id,t,surveyId,sequence,type,prompt.trim(),required,optionsJson==null?"[]":optionsJson); audit.record(t,actor.requireSubject(),"SURVEY_QUESTION_ADDED","survey_question",id.toString()); return jdbc.queryForObject("select id,survey_id,sequence_number,question_type,prompt,required,options_json::text from survey_question where tenant_id=? and id=?",(rs,n)->new SurveyQuestionView(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getBoolean(6),rs.getString(7)),t,id);}
@Transactional(readOnly=true) List<SurveyQuestionView> questions(UUID surveyId){auth.require(PermissionKey.SURVEYS_VIEW); UUID t=tenant.requireTenantId(); surveyForTenant(surveyId); return jdbc.query("select id,survey_id,sequence_number,question_type,prompt,required,options_json::text from survey_question where tenant_id=? and survey_id=? order by sequence_number",(rs,n)->new SurveyQuestionView(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getBoolean(6),rs.getString(7)),t,surveyId);}
@Transactional SurveyView createSurvey(String title,String desc,boolean anonymous,Instant opens,Instant closes){auth.require(PermissionKey.SURVEYS_MANAGE); if(closes!=null&&opens!=null&&!opens.isBefore(closes))throw new IllegalArgumentException("Survey closesAt must be after opensAt"); UUID t=tenant.requireTenantId(); UUID id=UUID.randomUUID(); jdbc.update("insert into survey(id,tenant_id,title,description,anonymous,opens_at,closes_at,status) values(?,?,?,?,?,?,?,'DRAFT')",id,t,title.trim(),desc,anonymous,opens,closes); audit.record(t,actor.requireSubject(),"SURVEY_CREATED","survey",id.toString()); return survey(id);}
@Transactional void publishSurvey(UUID id,long expectedVersion){auth.require(PermissionKey.SURVEYS_MANAGE); SurveyView s=survey(id); if(s.version()!=expectedVersion)throw new IllegalStateException("Survey was modified"); jdbc.update("update survey set status='OPEN',version=version+1 where tenant_id=? and id=?",tenant.requireTenantId(),id);}
@Transactional void respond(UUID surveyId,String answers,UUID membershipId){UUID t=tenant.requireTenantId(); SurveyView s=surveyForTenant(surveyId); auth.require(PermissionKey.SURVEYS_VIEW); if(!s.status().equals("OPEN"))throw new IllegalStateException("Survey is not open"); if(s.opensAt()!=null&&clock.instant().isBefore(s.opensAt()))throw new IllegalStateException("Survey not yet open"); if(s.closesAt()!=null&&clock.instant().isAfter(s.closesAt()))throw new IllegalStateException("Survey closed"); UUID respondent=s.anonymous()?null:membershipId; if(respondent!=null)memberships.requireActive(respondent); if(respondent!=null && jdbc.queryForObject("select count(*) from survey_response where tenant_id=? and survey_id=? and membership_id=?",Long.class,t,surveyId,respondent)>0) throw new IllegalStateException("Survey response already submitted"); jdbc.update("insert into survey_response(id,tenant_id,survey_id,membership_id,answers_json,submitted_at) values(?,?,?,?,cast(? as jsonb),?)",UUID.randomUUID(),t,surveyId,respondent,answers,clock.instant());}
@Transactional void feedback(UUID targetId,String targetType,Integer rating,String comments){auth.require(PermissionKey.FEEDBACK_MANAGE); if(rating<1||rating>5)throw new IllegalArgumentException("rating 1..5"); UUID t=tenant.requireTenantId(); UUID id=UUID.randomUUID(); jdbc.update("insert into feedback(id,tenant_id,target_type,target_id,author_membership_id,rating,comments,created_at,status) values(?,?,?,?,?,?,?,?,'SUBMITTED')",id,t,targetType,targetId,memberships.current().membershipId(),rating,comments,clock.instant()); audit.record(t,actor.requireSubject(),"FEEDBACK_SUBMITTED","feedback",id.toString());}
@Transactional(readOnly=true) List<FeedbackView> feedbackFor(UUID targetId,String targetType){auth.require(PermissionKey.FEEDBACK_VIEW); UUID t=tenant.requireTenantId(); return jdbc.query("select id,target_type,target_id,author_membership_id,rating,comments,created_at,status from feedback where tenant_id=? and target_id=? and target_type=? order by created_at desc",(rs,n)->new FeedbackView(rs.getObject(1,UUID.class),rs.getString(2),rs.getObject(3,UUID.class),rs.getObject(4,UUID.class),rs.getInt(5),rs.getString(6),rs.getObject(7,Instant.class),rs.getString(8)),t,targetId,targetType);}
private MentorshipView mentorship(UUID id){return jdbc.queryForObject("select id,mentor_membership_id,mentee_membership_id,goal,status,created_at,updated_at,version from mentorship where tenant_id=? and id=?",(rs,n)->new MentorshipView(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getObject(3,UUID.class),rs.getString(4),rs.getString(5),rs.getObject(6,Instant.class),rs.getObject(7,Instant.class),rs.getLong(8)),tenant.requireTenantId(),id);}
private SurveyView survey(UUID id){return surveyForTenant(id);}
private SurveyView surveyForTenant(UUID id){return jdbc.queryForObject("select id,title,description,anonymous,opens_at,closes_at,status,version from survey where tenant_id=? and id=?",(rs,n)->new SurveyView(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getBoolean(4),rs.getObject(5,Instant.class),rs.getObject(6,Instant.class),rs.getString(7),rs.getLong(8)),tenant.requireTenantId(),id);}
record MentorshipView(UUID id,UUID mentorMembershipId,UUID menteeMembershipId,String goal,String status,Instant createdAt,Instant updatedAt,long version){} record SurveyView(UUID id,String title,String description,boolean anonymous,Instant opensAt,Instant closesAt,String status,long version){} record SurveyQuestionView(UUID id,UUID surveyId,int sequence,String questionType,String prompt,boolean required,String optionsJson){} record FeedbackView(UUID id,String targetType,UUID targetId,UUID authorMembershipId,int rating,String comments,Instant createdAt,String status){}
}
